const assert=require('node:assert/strict');
const fs=require('node:fs');
const ts=require('typescript');
const mod={exports:{}};
new Function('module','exports',ts.transpileModule(fs.readFileSync(require('node:path').join(__dirname,'../lib/dashboard.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(mod,mod.exports);
const {dashboardTotals,indiaDate}=mod.exports;
const now=new Date('2026-09-21T04:30:00Z');
const loan=(id,date,status='active',balance=100)=>({id,given_date:date,next_due_date:'2026-09-20',status,balance,principal:200,customer_name:'Real customer'});
const loans=[loan('today','2026-09-21'),loan('week','2026-09-15'),loan('month','2026-09-01'),loan('older','2026-08-31'),loan('closed','2026-09-21','closed',0)];
const receipts=[{id:'india-midnight',amount:50,collected_at:Date.parse('2026-09-20T19:00:00Z')/1000},{id:'future',amount:999,collected_at:Date.parse('2026-09-22T00:00:00Z')/1000}];
assert.equal(indiaDate(new Date('2026-09-20T19:00:00Z')),'2026-09-21');
assert.equal(dashboardTotals(loans,receipts,'Today',now).issued.length,2);
assert.equal(dashboardTotals(loans,receipts,'Week',now).issued.length,3);
assert.equal(dashboardTotals(loans,receipts,'Month',now).issued.length,4);
const result=dashboardTotals(loans,receipts,'Today',now);
assert.equal(result.collected,50);assert.equal(result.portfolio,400);assert.equal(result.overdueBalance,400);
assert.equal(dashboardTotals([],[],'Today',now).collected,0);
assert.equal(dashboardTotals([],[],'Week',new Date('2026-01-02T04:30:00Z')).start,'2025-12-27');
console.log('PASS: real totals, India dates, period boundaries, closed loans, empty data and future receipt exclusion.');
