// Isolated login regression tests. No production database or network access.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),Module=require('node:module'),ts=require('typescript');
const root=path.resolve(__dirname,'..'),temp=fs.mkdtempSync(path.join(os.tmpdir(),'fundflow-login-test-'));
process.env.FUNDFLOW_LOCAL_DATA_PATH=path.join(temp,'data.json');process.env.FUNDFLOW_SESSION_SECRET='test-only-session-secret';process.env.FUNDFLOW_ADMIN_USER=' admin ';process.env.FUNDFLOW_ADMIN_PASSWORD='test-only-password';process.env.NODE_ENV='production';
for(const key of ['NEXT_PUBLIC_SUPABASE_URL','SUPABASE_SECRET_KEY','SUPABASE_SERVICE_ROLE_KEY'])delete process.env[key];
const resolve=Module._resolveFilename;Module._resolveFilename=function(name,...args){return resolve.call(this,name.startsWith('@/')?path.join(root,name.slice(2)):name,...args)};
Module._extensions['.ts']=function(mod,file){mod._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,file)};
global.fetch=()=>{throw new Error('Network forbidden in test')};
const route=require('../app/api/data/route.ts'),auth=require('../lib/auth.ts'),store=require('../lib/local-data-store.ts'),db=require('../lib/supabase-admin.ts');
const request=body=>new Request('http://localhost/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
(async()=>{
 const admin={id:'super-admin',name:'Admin',role:'admin'},agent={id:'agent-deepak',name:'Agent',role:'agent'};
 async function call(body,actor=admin){const r=request(body);r.headers.set('cookie',auth.createSessionCookie(actor,new Request('http://localhost')).split(';')[0]);return route.POST(r)}
 const rbac=require('../app/api/rbac/route.ts'),{defaultPolicy}=require('../lib/permissions.ts'),login=require('../app/api/auth/login/route.ts'),sessionRoute=require('../app/api/auth/session/route.ts');
 async function control(body,actor=admin){const r=request(body);r.headers.set('cookie',auth.createSessionCookie(actor,new Request('http://localhost')).split(';')[0]);return rbac.POST(r)}
 assert.equal((await control({action:'policy',policy:defaultPolicy},agent)).status,403);
 assert.equal((await control({action:'create_manager',name:'Manager',username:'manager1',password:'test-password-123'})).status,200);
 let data=await store.readLocalStore(),m=data.users.find(u=>u.username==='manager1'),manager={id:m.id,name:m.name,role:'manager'};
 assert.equal((await login.POST(request({username:'manager1',password:'test-password-123'}))).status,200);
 assert.equal((await call({action:'create_customer',name:'Manager customer',phone:'1234567890',occupation:'Shopkeeper'},manager)).status,200);
 assert.equal((await call({action:'create_agent',name:'Agent Test',phone:'1234567890',username:'agenttest',password:'longpassword'},manager)).status,200);
 assert.equal((await call({action:'delete_agent',id:'agent-deepak'},manager)).status,403);
 assert.equal((await call({action:'update_collection',id:'x',amount:10},manager)).status,403);
 assert.equal((await control({action:'create_manager',name:'Escalate',username:'escape',password:'longpassword'},manager)).status,403);
 const policy=structuredClone(defaultPolicy);policy.manager=policy.manager.filter(p=>p!=='create_customer');
 assert.equal((await control({action:'policy',policy})).status,200);
 assert.equal((await call({action:'create_customer',name:'No',phone:'123',occupation:'Worker'},manager)).status,403);
 const req=()=>new Request('http://localhost/api/data',{headers:{cookie:auth.createSessionCookie(manager,new Request('http://localhost')).split(';')[0]}});
 const snapshot=await(await route.GET(req())).json();assert.ok(snapshot.agents.length>=3);assert.ok(snapshot.customers.length>=4);
 policy.manager=[];assert.equal((await control({action:'policy',policy})).status,200);
 const restricted=await(await route.GET(req())).json();assert.equal(restricted.customers.length,0);assert.equal(restricted.loans.length,0);assert.equal(restricted.collections.length,0);
 assert.equal((await control({action:'manager_status',id:manager.id,enabled:false})).status,200);
 assert.equal((await route.GET(req())).status,401);assert.equal((await sessionRoute.GET(req())).status,401);
 assert.equal((await call({action:'assign_customer',customer_id:'customer-arjun',agent_id:'agent-meera'},agent)).status,403);
 assert.equal((await control({action:'policy',policy:{manager:[],agent:['create_agent']}})).status,400);
 assert.equal((await control({action:'policy',policy:{manager:['create_customer'],agent:[]}})).status,400);
 data=await store.readLocalStore();assert.ok(data.audit_logs.some(l=>l.action==='change_permissions'));assert.ok(data.audit_logs.some(l=>l.action==='manage_manager'));
 assert.equal((await control({action:'create_manager',name:'Editable',username:'editable',password:'original-password'})).status,200);
 data=await store.readLocalStore();const target=data.users.find(u=>u.username==='editable'),targetSession={id:target.id,name:target.name,role:'manager'},hash=target.password_hash;
 assert.equal((await control({action:'update_manager',id:target.id,name:'No',username:'forbidden'},targetSession)).status,403);
 assert.equal((await control({action:'delete_manager',id:target.id},agent)).status,403);
 assert.equal((await control({action:'update_manager',id:target.id,name:'Updated',username:'edited',password:''})).status,200);
 data=await store.readLocalStore();assert.equal(data.users.find(u=>u.id===target.id).password_hash,hash);
 assert.equal((await control({action:'update_manager',id:target.id,name:'Updated',username:'manager1'})).status,400);
 assert.equal((await control({action:'update_manager',id:target.id,name:'Updated',username:'edited',password:'short'})).status,400);
 assert.equal((await control({action:'update_manager',id:target.id,name:'Updated',username:'edited',password:'replacement-password'})).status,200);
 assert.equal((await login.POST(request({username:'edited',password:'replacement-password'}))).status,200);
 assert.equal((await login.POST(request({username:'edited',password:'original-password'}))).status,401);
 assert.equal((await control({action:'delete_manager',id:'agent-deepak'})).status,400);
 const beforeDelete=await store.readLocalStore();
 assert.equal((await control({action:'delete_manager',id:target.id})).status,200);
 const stale=new Request('http://localhost/api/data',{headers:{cookie:auth.createSessionCookie(targetSession,new Request('http://localhost')).split(';')[0]}});
 assert.equal((await route.GET(stale)).status,401);
 assert.equal((await login.POST(request({username:'edited',password:'replacement-password'}))).status,401);
 assert.equal((await control({action:'manager_status',id:target.id,enabled:true})).status,400);
 assert.equal((await control({action:'update_manager',id:target.id,name:'Restore',username:'restore'})).status,400);
 data=await store.readLocalStore();assert.equal(data.users.find(u=>u.id===target.id).role,'deleted_manager');assert.equal(data.users.find(u=>u.id===target.id).password_hash,null);
 assert.deepEqual(data.collections,beforeDelete.collections);assert.deepEqual(data.loans,beforeDelete.loans);
 assert.ok(data.audit_logs.some(l=>l.metadata.activity==='Deleted manager account'));
 assert.ok(!JSON.stringify(data.audit_logs).includes('replacement-password'));
 const listReq=new Request('http://localhost/api/rbac',{headers:{cookie:auth.createSessionCookie(admin,new Request('http://localhost')).split(';')[0]}});
 assert.ok(!(await(await rbac.GET(listReq)).json()).managers.some(u=>u.id===target.id));
 console.log('PASS: manager login/creation/default permissions, escalation denial, immediate revocation, dataset redaction, disabled sessions and audited RBAC changes.');})().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>{if(path.dirname(path.resolve(temp))===path.resolve(os.tmpdir())&&path.basename(temp).startsWith('fundflow-login-test-'))fs.rmSync(temp,{recursive:true,force:true})});
