'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, Bell, CalendarDays, Check, ChevronDown, CircleDollarSign, Clock3, Download, FileCheck2, FileText, HandCoins, LayoutDashboard, Menu, MessageCircle, MoreHorizontal, Plus, Search, Settings, ShieldCheck, Smartphone, Trash2, Pencil, Upload, TrendingUp, UserRound, UsersRound, WalletCards, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';

type Role = 'admin' | 'agent' | 'customer';
type Modal = 'loan' | 'customer' | 'payment' | 'topup' | 'exception' | 'settings' | 'access' | 'assignment' | 'reminder' | 'topupDecision' | null;

const loans = [
  { id: 'LN-2048', name: 'Arjun Mehta', initials: 'AM', amount: '₹2,50,000', balance: '₹1,82,400', due: 'Today', status: 'Due today', tone: 'amber' },
  { id: 'LN-2047', name: 'Priya Sharma', initials: 'PS', amount: '₹1,20,000', balance: '₹84,000', due: '08 Sep 2026', status: 'On track', tone: 'green' },
  { id: 'LN-2046', name: 'Ravi Kumar', initials: 'RK', amount: '₹4,00,000', balance: '₹3,44,800', due: '02 Sep 2026', status: 'Overdue', tone: 'red' },
  { id: 'LN-2045', name: 'Neha Patel', initials: 'NP', amount: '₹75,000', balance: '₹22,500', due: '12 Sep 2026', status: 'On track', tone: 'green' },
];

type NavItem = { label: string; icon: typeof LayoutDashboard; badge?: string };

const adminNav: NavItem[] = [
  { label: 'Overview', icon: LayoutDashboard }, { label: 'Customers', icon: UsersRound },
  { label: 'Loans', icon: WalletCards, badge: '24' }, { label: 'Collections', icon: HandCoins },
  { label: 'Agents', icon: UserRound }, { label: 'Reports', icon: FileText },
];

const roleNav: Record<Role, NavItem[]> = {
  admin: adminNav,
  agent: [{ label: 'My route', icon: LayoutDashboard }, { label: 'Assigned customers', icon: UsersRound }, { label: 'Collections', icon: HandCoins }, { label: 'My reports', icon: FileText }],
  customer: [{ label: 'My loan', icon: LayoutDashboard }, { label: 'Repayments', icon: HandCoins }, { label: 'Top-up requests', icon: WalletCards }, { label: 'My reports', icon: FileText }],
};

const roleName = { admin: 'Super Admin', agent: 'Collection Agent', customer: 'Customer' };
const customerIdByName:Record<string,string>={'Arjun Mehta':'customer-arjun','Priya Sharma':'customer-priya','Ravi Kumar':'customer-ravi','Neha Patel':'customer-neha'};
const agentIdByName:Record<string,string>={'Deepak Singh':'agent-deepak','Meera Joshi':'agent-meera','Akash Verma':'agent-akash'};
async function postData(payload:Record<string,unknown>) { const response=await fetch('/api/data',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)}); if(!response.ok) { throw new Error((await response.json()).error||'Database update failed'); } return response.json(); }
async function getData() { const response=await fetch('/api/data',{signal:AbortSignal.timeout(15000)}); if(!response.ok) { throw new Error((await response.json()).error||'Could not load finance data'); } return response.json(); }
const money=(value:number)=>'₹'+Number(value||0).toLocaleString('en-IN');
const refreshData=()=>window.dispatchEvent(new Event('fundflow-data'));


export default function Home() {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [active, setActive] = useState('Overview');
  const [role, setRole] = useState<Role>('admin');
  const [modal, setModal] = useState<Modal>(null);
  const [toast, setToast] = useState('');
  const [period, setPeriod] = useState('Today');
  const [assignments, setAssignments] = useState<Record<string,string>>({});
  const [selectedCustomer, setSelectedCustomer] = useState('Arjun Mehta');
  const [selectedCustomerId, setSelectedCustomerId] = useState('customer-arjun');
  const [selectedAgent, setSelectedAgent] = useState('Deepak Singh');
  const [reminderChannel, setReminderChannel] = useState<'SMS'|'WhatsApp'>('SMS');
  const [topupDecision, setTopupDecision] = useState<'approve'|'decline'>('approve');
  const [topupStatus, setTopupStatus] = useState<'Pending'|'Approved'|'Declined'>('Pending');
  const [brandVersion,setBrandVersion]=useState(Date.now());
  const [customLogo,setCustomLogo]=useState(false);
  const nav = roleNav[role];
  const changeRole = (next: Role) => { setRole(next); setActive(roleNav[next][0].label); };
  const finish = (message: string) => { setModal(null); setToast(message); window.setTimeout(() => setToast(''), 2800); };
  useEffect(()=>{const loadBrand=async()=>{const version=Date.now();setBrandVersion(version);try{const logo=await fetch('/api/branding/logo',{cache:'no-store'});setCustomLogo(logo.ok);}catch{setCustomLogo(false);}try{const favicon=await fetch('/api/branding/favicon',{cache:'no-store'});if(favicon.ok){let link=document.querySelector('link[rel="icon"]') as HTMLLinkElement|null;if(!link){link=document.createElement('link');link.rel='icon';document.head.appendChild(link);}link.href='/api/branding/favicon?v='+version;}}catch{}};loadBrand();window.addEventListener('fundflow-brand',loadBrand);return()=>window.removeEventListener('fundflow-brand',loadBrand);},[]);
  return <main className="min-h-screen bg-[#f3f7f5] text-[#15261f]">
    <aside className={`fixed inset-y-0 left-0 z-40 flex w-[250px] flex-col bg-[#0c3327] text-white transition-transform lg:translate-x-0 ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'}`}>
      <div className="flex h-[76px] items-center justify-between border-b border-white/10 px-6"><div className="flex items-center gap-3">{customLogo?<img src={"/api/branding/logo?v="+brandVersion} alt="FundFlow logo" className="size-9 rounded-xl bg-white object-contain p-1"/>:<div className="grid size-9 place-items-center rounded-xl bg-[#d9ff54] text-[#16372b]"><CircleDollarSign className="size-5" /></div>}<div><div className="text-[17px] font-bold tracking-tight">FundFlow</div><div className="text-[10px] font-medium uppercase tracking-[.16em] text-white/50">Finance OS</div></div></div><button className="lg:hidden" onClick={() => setSidebarOpen(false)} aria-label="Close menu"><X className="size-5" /></button></div>
      <div className="px-4 py-5"><p className="px-3 pb-2 text-[10px] font-semibold uppercase tracking-[.17em] text-white/40">Workspace</p><nav className="space-y-1">{nav.map((item) => <button key={item.label} onClick={() => {setActive(item.label);setSidebarOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition ${active === item.label ? 'bg-white text-[#12372b] shadow-sm' : 'text-white/70 hover:bg-white/8 hover:text-white'}`}><item.icon className="size-4" /><span>{item.label}</span>{item.badge && <span className="ml-auto rounded-full bg-[#d9ff54] px-2 py-0.5 text-[10px] font-bold text-[#16372b]">{item.badge}</span>}</button>)}</nav></div>
      <div className="mt-auto p-4"><button onClick={() => role === 'admin' ? setModal('settings') : finish('Profile settings opened')} className="mb-3 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-white/65 hover:bg-white/8"><Settings className="size-4" /> Settings</button><div className="rounded-2xl border border-white/10 bg-white/7 p-3"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-[#d9ff54] text-xs font-bold text-[#183c2e]">{role === 'admin' ? 'SK' : role === 'agent' ? 'DS' : 'AM'}</div><div className="min-w-0"><p className="truncate text-sm font-semibold">{role === 'admin' ? 'Suresh Kumar' : role === 'agent' ? 'Deepak Singh' : 'Arjun Mehta'}</p><p className="text-xs text-white/45">{roleName[role]}</p></div><ChevronDown className="ml-auto size-4 text-white/50" /></div></div></div>
    </aside>
    <div className="lg:pl-[250px]">
      <header className="sticky top-0 z-30 flex h-[76px] items-center gap-3 border-b border-[#dce6e1] bg-white/90 px-5 backdrop-blur-xl lg:px-8"><button className="lg:hidden" onClick={() => setSidebarOpen(true)} aria-label="Open menu"><Menu className="size-5" /></button><div className="relative hidden max-w-sm flex-1 md:block"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-[#789087]" /><input className="h-10 w-full rounded-xl border border-[#dce5e0] bg-[#f7faf8] pl-10 pr-4 text-sm outline-none focus:border-[#1e6e50]" placeholder="Search records..." /></div><div className="ml-auto flex items-center gap-2"><label className="hidden text-[10px] font-bold uppercase tracking-wider text-[#7a8d85] sm:block">View as</label><select aria-label="Switch portal role" value={role} onChange={(e) => changeRole(e.target.value as Role)} className="h-10 rounded-xl border border-[#d7e2dd] bg-white px-3 text-xs font-semibold outline-none"><option value="admin">Super Admin</option><option value="agent">Collection Agent</option><option value="customer">Customer</option></select><button className="relative grid size-9 place-items-center rounded-xl border border-[#dce5e0] bg-white"><Bell className="size-4" /><span className="absolute right-2 top-2 size-1.5 rounded-full bg-[#f26a4f] ring-2 ring-white" /></button><Button onClick={() => setModal(role === 'admin' ? 'loan' : role === 'agent' ? 'payment' : 'topup')} className="h-10 rounded-xl bg-[#153d30] px-4 hover:bg-[#205a46]"><Plus /> <span className="hidden sm:inline">{role === 'admin' ? 'New loan' : role === 'agent' ? 'Record payment' : 'Request top-up'}</span></Button></div></header>
      <section className="p-5 lg:p-8">{role !== 'admin' ? <RolePortal role={role} active={active} period={period} setPeriod={setPeriod} open={setModal} notify={finish} /> : active !== 'Overview' ? <AdminSection active={active} period={period} setPeriod={setPeriod} open={setModal} notify={finish} assignments={assignments} assignCustomer={(name,id) => { setSelectedCustomer(name); setSelectedCustomerId(id||customerIdByName[name]||''); setModal('assignment'); }} manageAgent={(name) => { setSelectedAgent(name); setModal('access'); }} /> : <><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.14em] text-[#6e857c]">Friday, 4 September</p><h1 className="text-3xl font-bold tracking-[-.035em] text-[#122a21]">Good morning, Suresh</h1><p className="mt-1.5 text-sm text-[#6c8078]">Here’s what’s happening across your lending portfolio.</p></div><Period value={period} onChange={setPeriod} /></div>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={WalletCards} label="Active portfolio" value="₹48.26L" note="+8.4% this month" positive /><Metric icon={HandCoins} label="Collected today" value="₹1.84L" note="74% of ₹2.48L target" progress={74} /><Metric icon={TrendingUp} label="Interest earned" value="₹3.62L" note="+12.1% vs last month" positive /><Metric icon={ShieldCheck} label="Overdue amount" value="₹86,400" note="8 accounts need attention" warning /></div>
        <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(340px,.75fr)]"><div className="overflow-hidden rounded-2xl border border-[#dbe5e0] bg-white shadow-[0_12px_30px_rgba(17,47,36,.035)]"><div className="flex items-center justify-between border-b border-[#e4ebe7] px-5 py-4"><div><h2 className="font-bold">Recent loans</h2><p className="mt-0.5 text-xs text-[#7a8c85]">Live repayment and due-date status</p></div><button onClick={()=>setActive('Loans')} className="text-xs font-bold text-[#176447] hover:underline">View all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] table-fixed text-left"><colgroup><col className="w-[15%]"/><col className="w-[10%]"/><col className="w-[10%]"/><col className="w-[10%]"/><col className="w-[16%]"/></colgroup><thead className="bg-[#f7faf8] text-[10px] font-bold uppercase tracking-[.11em] text-[#81928b]"><tr><th className="px-3 py-3">Customer</th><th className="px-4 py-3">Principal</th><th className="px-4 py-3">Balance</th><th className="px-4 py-3">Next due</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{loans.map((loan) => <tr key={loan.id} className="border-t border-[#edf1ef] text-sm hover:bg-[#f9fbfa]"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full bg-[#e8f4ed] text-xs font-bold text-[#27624b]">{loan.initials}</div><div><p className="font-semibold">{loan.name}</p><p className="text-[11px] text-[#86968f]">{loan.id}</p></div></div></td><td className="px-4 py-4 font-medium">{loan.amount}</td><td className="px-4 py-4 font-semibold">{loan.balance}</td><td className="px-4 py-4 text-[#62766e]">{loan.due}</td><td className="px-4 py-4"><span className={`status status-${loan.tone}`}>{loan.status}</span></td></tr>)}</tbody></table></div></div>
          <div className="space-y-6"><div className="rounded-2xl bg-[#153d30] p-5 text-white shadow-[0_14px_34px_rgba(20,61,48,.18)]"><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-white/55">Today’s collection</p><p className="mt-2 text-3xl font-bold tracking-tight">₹1,84,200</p></div><div className="grid size-10 place-items-center rounded-xl bg-[#d9ff54] text-[#16382b]"><HandCoins className="size-5" /></div></div><div className="mt-6 flex items-end gap-1"><div className="h-6 flex-1 rounded-sm bg-white/15"/><div className="h-9 flex-1 rounded-sm bg-white/20"/><div className="h-5 flex-1 rounded-sm bg-white/15"/><div className="h-12 flex-1 rounded-sm bg-[#d9ff54]"/><div className="h-8 flex-1 rounded-sm bg-white/20"/><div className="h-10 flex-1 rounded-sm bg-white/25"/><div className="h-7 flex-1 rounded-sm bg-white/15"/></div><div className="mt-3 flex justify-between text-[10px] text-white/45"><span>8 AM</span><span>12 PM</span><span>Now</span></div></div><div className="rounded-2xl border border-[#dbe5e0] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Due today</h2><p className="mt-0.5 text-xs text-[#82918b]">12 scheduled repayments</p></div><span className="rounded-full bg-[#fff2d5] px-2.5 py-1 text-xs font-bold text-[#94610b]">₹2.48L</span></div><div className="mt-5 space-y-4"><ProgressRow name="Collected" value="₹1.84L" width="74%" color="#2d8b63"/><ProgressRow name="Pending" value="₹54,000" width="22%" color="#e6a83c"/><ProgressRow name="Exceptions" value="₹10,000" width="4%" color="#ea725c"/></div><div className="mt-4 flex gap-2"><Button onClick={()=>{setReminderChannel('SMS');setModal('reminder')}} variant="outline" size="sm" className="flex-1"><Smartphone/> SMS</Button><Button onClick={()=>{setReminderChannel('WhatsApp');setModal('reminder')}} variant="outline" size="sm" className="flex-1"><MessageCircle/> WhatsApp</Button></div></div><div className="rounded-2xl border border-[#dbe5e0] bg-white p-5"><div className="flex items-center justify-between"><div><h2 className="font-bold">Top-up approval</h2><p className="mt-0.5 text-xs text-[#82918b]">Arjun Mehta · ₹50,000 · Fixed</p></div><span className={topupStatus === 'Approved' ? 'status status-green' : topupStatus === 'Declined' ? 'status status-red' : 'status status-amber'}>{topupStatus}</span></div><p className="mt-3 text-xs text-[#6f827a]">Existing property security · requested today</p>{topupStatus === 'Pending' ? <div className="mt-4 flex gap-2"><Button onClick={()=>{setTopupDecision('approve');setModal('topupDecision')}} size="sm" className="flex-1"><Check/> Approve</Button><Button onClick={()=>{setTopupDecision('decline');setModal('topupDecision')}} variant="outline" size="sm">Decline</Button></div> : <div className="mt-4 rounded-xl bg-[#f3f7f5] p-3 text-xs text-[#5f766c]">Decision recorded by Suresh Kumar · today</div>}</div></div>
        </div></>}
      </section>
    </div>{sidebarOpen && <button aria-label="Close navigation" className="fixed inset-0 z-30 bg-black/35 lg:hidden" onClick={() => setSidebarOpen(false)} />}
    {modal === 'settings' || modal === 'access' || modal === 'assignment' ? <AdminToolDialog modal={modal} close={() => setModal(null)} finish={finish} selectedCustomer={selectedCustomer} selectedAgent={selectedAgent} saveAssignment={async(agent) => { try { await postData({action:'assign_customer',customer_id:selectedCustomerId,agent_id:agentIdByName[agent]}); setAssignments((current) => ({...current, [selectedCustomer]: agent})); refreshData(); finish(selectedCustomer + ' assigned to ' + agent); } catch(error) { finish(error instanceof Error?error.message:'Assignment failed'); } }} /> : modal === 'reminder' ? <ReminderDialog channel={reminderChannel} close={()=>setModal(null)} finish={finish}/> : modal === 'topupDecision' ? <TopupDecisionDialog decision={topupDecision} close={()=>setModal(null)} finish={(message)=>{setTopupStatus(topupDecision === 'approve' ? 'Approved' : 'Declined');finish(message)}}/> : <ActionDialog modal={modal} close={() => setModal(null)} finish={finish} />}
    {toast && <div role="status" className="fixed bottom-5 right-5 z-[80] flex items-center gap-3 rounded-xl bg-[#123b2d] px-4 py-3 text-sm font-semibold text-white shadow-2xl"><span className="grid size-6 place-items-center rounded-full bg-[#d9ff54] text-[#153d30]"><Check className="size-4" /></span>{toast}</div>}
  </main>;
}

function Metric({ icon: Icon, label, value, note, positive, warning, progress }: { icon: typeof WalletCards; label: string; value: string; note: string; positive?: boolean; warning?: boolean; progress?: number }) { return <div className="rounded-2xl border border-[#dbe5e0] bg-white p-5 shadow-[0_10px_30px_rgba(17,47,36,.03)]"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-[#71847c]">{label}</p><div className={`grid size-9 place-items-center rounded-xl ${warning ? 'bg-[#fff0e9] text-[#c95741]' : 'bg-[#e7f5ed] text-[#237253]'}`}><Icon className="size-4" /></div></div><p className="mt-3 text-[26px] font-bold tracking-[-.035em]">{value}</p>{progress ? <><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#eaf0ed]"><div className="h-full rounded-full bg-[#2d8b63]" style={{width: `${progress}%`}} /></div><p className="mt-2 text-[11px] text-[#7d8e87]">{note}</p></> : <p className={`mt-2 text-[11px] ${positive ? 'text-[#25845d]' : warning ? 'text-[#ca6049]' : 'text-[#7d8e87]'}`}>{note}</p>}</div> }
function ProgressRow({name, value, width, color}: {name: string; value: string; width: string; color: string}) { return <div><div className="mb-1.5 flex justify-between text-xs"><span className="text-[#71837c]">{name}</span><span className="font-bold">{value}</span></div><div className="h-1.5 rounded-full bg-[#eef2f0]"><div className="h-full rounded-full" style={{width, backgroundColor: color}} /></div></div> }

function Period({value,onChange}:{value:string;onChange:(v:string)=>void}) { return <div className="flex w-fit rounded-xl border border-[#d7e2dd] bg-white p-1 text-xs font-semibold">{['Today','Week','Month'].map(p=><button key={p} onClick={()=>onChange(p)} className={`rounded-lg px-3 py-2 ${value===p?'bg-[#143b2e] text-white':'text-[#6a7d75]'}`}>{p}</button>)}</div> }

const customers = [
  ['Arjun Mehta','+91 98765 43010','2','₹1,82,400','Deepak Singh','Verified'],
  ['Priya Sharma','+91 97654 22981','1','₹84,000','Meera Joshi','Verified'],
  ['Ravi Kumar','+91 99887 10242','1','₹3,44,800','Deepak Singh','Review'],
  ['Neha Patel','+91 91234 56908','1','₹22,500','Meera Joshi','Verified'],
];
const payments = [
  ['RC-8391','Arjun Mehta','₹12,500','UPI','Deepak Singh','10:42 AM'],['RC-8390','Priya Sharma','₹8,000','Cash','Meera Joshi','10:18 AM'],['RC-8389','Neha Patel','₹6,250','Bank transfer','Meera Joshi','9:36 AM'],
];

function PageHead({eyebrow,title,subtitle,action}:{eyebrow:string;title:string;subtitle:string;action?:React.ReactNode}) { return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-xs font-bold uppercase tracking-[.14em] text-[#71857c]">{eyebrow}</p><h1 className="text-3xl font-bold tracking-[-.035em]">{title}</h1><p className="mt-1.5 text-sm text-[#6c8078]">{subtitle}</p></div>{action}</div> }
function Card({children,className=''}:{children:React.ReactNode;className?:string}) { return <div className={`rounded-2xl border border-[#dbe5e0] bg-white shadow-[0_10px_28px_rgba(17,47,36,.03)] ${className}`}>{children}</div> }

function AdminSection({active,period,setPeriod,open,notify,assignments,assignCustomer,manageAgent}:{active:string;period:string;setPeriod:(v:string)=>void;open:(m:Modal)=>void;notify:(m:string)=>void;assignments:Record<string,string>;assignCustomer:(name:string,id?:string)=>void;manageAgent:(name:string)=>void}) {
  if(active==='Customers') return <CustomerSection open={open} notify={notify} assignments={assignments} assignCustomer={assignCustomer}/>;
  if(active==='Loans') return <LoanSection open={open} notify={notify}/>;
  if(active==='Collections') return <CollectionSection open={open} notify={notify}/>;
  if(active==='Agents') return <AgentSection notify={notify} manageAgent={manageAgent}/>;
  return <ReportSection period={period} setPeriod={setPeriod} notify={notify}/>;
}

function ReportSection({period,setPeriod,notify}:{period:string;setPeriod:(v:string)=>void;notify:(m:string)=>void}) {
  const [data,setData]=useState<any>({customers:[],loans:[],collections:[],agents:[],summary:{}});const [loading,setLoading]=useState(true);
  const load=async()=>{try{setData(await getData());}catch(error){notify(error instanceof Error?error.message:'Report loading failed');}finally{setLoading(false);}};
  useEffect(()=>{load();const refresh=()=>load();window.addEventListener('fundflow-data',refresh);return()=>window.removeEventListener('fundflow-data',refresh);},[]);
  const csv=(name:string,headers:string[],rows:any[][])=>{const escaped=(value:any)=>'"'+String(value??'').replace(/"/g,'""')+'"';downloadCsv('fundflow-'+name.toLowerCase()+'-report.csv',headers.join(',')+'\n'+rows.map(row=>row.map(escaped).join(',')).join('\n'));notify(name+' report exported');};
  const exportCustomers=()=>csv('Customers',['ID','Customer','Phone','Email','Agent','Active loans','Outstanding'],data.customers.map((x:any)=>[x.id,x.name,x.phone,x.email,x.agent_name,x.active_loans,x.outstanding]));
  const exportLoans=()=>csv('Loans',['Loan ID','Customer','Principal','Paid','Balance','Interest type','Interest rate','Frequency','Given date','Next due','Status'],data.loans.map((x:any)=>[x.id,x.customer_name,x.principal,x.paid,x.balance,x.interest_type,x.interest_rate,x.repayment_frequency,x.given_date,x.next_due_date,x.status]));
  const exportCollections=()=>csv('Collections',['Receipt','Customer','Loan','Amount','Method','Agent','Collected at','Remarks'],data.collections.map((x:any)=>[x.id,x.customer_name,x.loan_id,x.amount,x.method,x.agent_name,new Date(x.collected_at*1000).toLocaleString(),x.remarks]));
  const exportAgents=()=>csv('Agents',['Agent ID','Agent','Phone','Email','Assigned customers','Collected'],data.agents.map((x:any)=>[x.id,x.name,x.phone,x.email,x.assigned,x.collected]));
  const s=data.summary||{};
  return <><PageHead eyebrow="Portfolio intelligence" title="Reports" subtitle="Exact live values from every stored customer, loan, collection and agent record." action={<Period value={period} onChange={setPeriod}/>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={UsersRound} label="Customers" value={String(s.customer_count||0)} note="Exact borrower count"/><Metric icon={WalletCards} label="Amount disbursed" value={money(s.disbursed||0)} note={String(s.loan_count||0)+' loan records'} positive/><Metric icon={HandCoins} label="Amount collected" value={money(s.collected||0)} note={String(data.collections.length||0)+' posted receipts'} positive/><Metric icon={AlertTriangle} label="Outstanding" value={money(s.outstanding||0)} note="Exact open-loan balance" warning/></div>
  <Card className="mt-6 p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><b>Download complete reports</b><p className="mt-1 text-xs text-[#7c8d86]">{loading?'Calculating exact values...':'Every export uses the records shown below.'}</p></div><div className="flex flex-wrap gap-2"><Button onClick={exportCustomers} variant="outline"><Download/> Customers</Button><Button onClick={exportLoans} variant="outline"><Download/> Loans</Button><Button onClick={exportCollections} variant="outline"><Download/> Collections</Button><Button onClick={exportAgents} variant="outline"><Download/> Agents</Button></div></div></Card>
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><ReportTable title={'Customers · '+data.customers.length} headers={['Customer','Loans','Outstanding','Agent']} rows={data.customers.map((x:any)=>[x.name,String(x.active_loans),money(x.outstanding),x.agent_name||'Unassigned'])}/><ReportTable title={'Loans · '+data.loans.length} headers={['Loan / customer','Principal','Paid','Balance']} rows={data.loans.map((x:any)=>[x.id+' · '+x.customer_name,money(x.principal),money(x.paid),money(x.balance)])}/><ReportTable title={'Collections · '+data.collections.length} headers={['Receipt / customer','Amount','Method','Agent']} rows={data.collections.map((x:any)=>[x.id+' · '+x.customer_name,money(x.amount),x.method,x.agent_name])}/><ReportTable title={'Agents · '+data.agents.length} headers={['Agent','Assigned','Collected','Phone']} rows={data.agents.map((x:any)=>[x.name,String(x.assigned),money(x.collected),x.phone])}/></div></>;
}

function ReportTable({title,headers,rows}:{title:string;headers:string[];rows:string[][]}) {
  return <Card className="overflow-x-auto"><div className="border-b border-[#e4ebe7] px-5 py-4"><b>{title}</b></div><table className="w-full min-w-[560px] text-left text-xs"><thead><tr className="bg-[#f7faf8] text-[10px] uppercase tracking-wider text-[#7f9189]">{headers.map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index} className="border-t border-[#edf1ef]">{row.map((value,i)=><td key={i} className={'px-4 py-3 '+(i===0?'font-semibold':'')}>{value}</td>)}</tr>)}</tbody></table>{rows.length===0&&<div className="p-6 text-center text-xs text-[#73867d]">No records available.</div>}</Card>;
}
function LoanSection({open,notify}:{open:(m:Modal)=>void;notify:(message:string)=>void}) {
  const [items,setItems]=useState<any[]>([]);const [selected,setSelected]=useState<any|null>(null);const [editing,setEditing]=useState(false);const [rate,setRate]=useState('');const [due,setDue]=useState('');const [remarks,setRemarks]=useState('');
  const load=async()=>{try{const data=await getData();setItems(data.loans);if(selected){const updated=data.loans.find((x:any)=>x.id===selected.id);if(updated)setSelected(updated);}}catch(error){notify(error instanceof Error?error.message:'Loan loading failed');}};
  useEffect(()=>{load();const refresh=()=>load();window.addEventListener('fundflow-data',refresh);return()=>window.removeEventListener('fundflow-data',refresh);},[]);
  const openDetail=(loan:any)=>{setSelected(loan);setEditing(false);setRate(String(loan.interest_rate));setDue(loan.next_due_date);setRemarks(loan.remarks||'');};
  const save=async()=>{if(!selected)return;try{await postData({action:'update_loan',id:selected.id,interest_rate:Number(rate),next_due_date:due,remarks});await load();refreshData();setEditing(false);notify('Loan '+selected.id+' updated');}catch(error){notify(error instanceof Error?error.message:'Loan update failed');}};
  const exportLoans=()=>{const csv='Loan ID,Customer,Principal,Paid,Balance,Interest Type,Interest Rate,Frequency,Given Date,Next Due,Security,Status\n'+items.map(l=>[l.id,l.customer_name,l.principal,l.paid,l.balance,l.interest_type,l.interest_rate,l.repayment_frequency,l.given_date,l.next_due_date,l.security_file_key,l.status].map((v:any)=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');downloadCsv('fundflow-loans.csv',csv);notify('Loan export downloaded');};
  const tone=(loan:any)=>loan.status==='overdue'?'red':loan.next_due_date==='2026-09-05'?'amber':'green';
  return <><PageHead eyebrow="Portfolio" title="All loans" subtitle="Fixed and floating loans, security files, balances and schedules." action={<div className="flex gap-2"><Button onClick={exportLoans} variant="outline" className="h-10"><Download/> Export loans</Button><Button onClick={()=>open('loan')} className="h-10 rounded-xl"><Plus/> New loan</Button></div>}/><div className="mb-4 flex gap-2"><span className="status status-green">{items.filter(x=>x.status==='active').length} active</span><span className="status status-red">{items.filter(x=>x.status==='overdue').length} overdue</span></div><Card className="overflow-x-auto"><table className="w-full min-w-[980px] table-fixed text-left text-sm"><thead><tr className="bg-[#f7faf8] text-[10px] uppercase tracking-wider text-[#7f9189]">{['Customer / ID','Principal','Paid','Balance','Interest','Return basis','Security','Status'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{items.map(l=><tr key={l.id} className="border-t border-[#edf1ef] hover:bg-[#f8fbf9]"><td className="px-4 py-4"><button onClick={()=>openDetail(l)} className="text-left hover:text-[#176447]"><b>{l.customer_name}</b><p className="text-xs text-[#85958e]">{l.id}</p></button></td><td className="px-4">{money(l.principal)}</td><td className="px-4">{money(l.paid)}</td><td className="px-4 font-bold">{money(l.balance)}</td><td className="px-4 capitalize">{l.interest_type+' · '+l.interest_rate+'%'}</td><td className="px-4 capitalize">{l.repayment_frequency}</td><td className="px-4"><button onClick={()=>openDetail(l)} className="flex items-center gap-1 font-medium text-[#176447]"><FileCheck2 className="size-4"/> View</button></td><td className="px-4"><span className={'status status-'+tone(l)}>{l.status==='overdue'?'Overdue':l.status==='closed'?'Settled':'On track'}</span></td></tr>)}</tbody></table></Card>
  <Dialog open={Boolean(selected)} onOpenChange={(value)=>{if(!value){setSelected(null);setEditing(false)}}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">{selected&&<><DialogHeader><div className="flex items-start justify-between gap-4 pr-8"><div><DialogTitle>{selected.customer_name+' · '+selected.id}</DialogTitle><DialogDescription>Complete loan account, repayment and security information.</DialogDescription></div><Button onClick={()=>setEditing(!editing)} variant="outline" size="sm"><Pencil/> {editing?'Cancel edit':'Edit loan'}</Button></div></DialogHeader><div className="grid gap-4 sm:grid-cols-3"><Detail label="Principal" value={money(selected.principal)}/><Detail label="Amount paid" value={money(selected.paid)}/><Detail label="Balance" value={money(selected.balance)}/><Detail label="Given date" value={selected.given_date}/><Detail label="Return basis" value={selected.repayment_frequency}/><Detail label="Assigned agent" value={selected.agent_name||'Unassigned'}/></div>{editing?<div className="mt-2 grid gap-4 sm:grid-cols-2"><Field label="Interest rate (%)"><Input type="number" value={rate} onChange={(e)=>setRate(e.target.value)}/></Field><Field label="Next due date"><Input type="date" value={due} onChange={(e)=>setDue(e.target.value)}/></Field><Field label="Loan remarks" wide><Textarea value={remarks} onChange={(e)=>setRemarks(e.target.value)}/></Field></div>:<div className="mt-2 grid gap-4 sm:grid-cols-2"><Detail label="Interest" value={selected.interest_type+' · '+selected.interest_rate+'%'}/><Detail label="Next mandatory due" value={selected.next_due_date}/><Detail label="Purpose / remarks" value={selected.remarks||'—'} wide/></div>}<div className="mt-2 rounded-2xl border border-[#dbe5e0] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#70847b]">Attached security document</p><div className="mt-3 flex items-center gap-3 rounded-xl bg-[#f3f8f5] p-3"><FileText className="size-5 text-[#246b4e]"/><div><b className="text-sm">{selected.security_file_key||'No document attached'}</b><p className="text-xs text-[#71857c]">{selected.security_type+' security'}</p></div>{selected.security_file_key&&<Button onClick={()=>notify(selected.security_file_key+' opened')} variant="outline" size="sm" className="ml-auto">View document</Button>}</div></div><DialogFooter>{editing&&<Button onClick={save}>Save loan changes</Button>}<Button variant="outline" onClick={()=>setSelected(null)}>Close</Button></DialogFooter></>}</DialogContent></Dialog></>;
}
function CollectionSection({open,notify}:{open:(m:Modal)=>void;notify:(message:string)=>void}) {
  const [items,setItems]=useState<any[]>([]);const [selected,setSelected]=useState<any|null>(null);const [editing,setEditing]=useState(false);const [amount,setAmount]=useState('');const [method,setMethod]=useState('');const [remarks,setRemarks]=useState('');
  const load=async()=>{try{const data=await getData();setItems(data.collections);if(selected){const updated=data.collections.find((x:any)=>x.id===selected.id);if(updated)setSelected(updated);}}catch(error){notify(error instanceof Error?error.message:'Collection loading failed');}};
  useEffect(()=>{load();const refresh=()=>load();window.addEventListener('fundflow-data',refresh);return()=>window.removeEventListener('fundflow-data',refresh);},[]);
  const openReceipt=(receipt:any)=>{setSelected(receipt);setEditing(false);setAmount(String(receipt.amount));setMethod(receipt.method);setRemarks(receipt.remarks||'');};
  const save=async()=>{if(!selected)return;try{await postData({action:'update_collection',id:selected.id,amount,method,remarks});await load();refreshData();setEditing(false);notify('Receipt '+selected.id+' updated');}catch(error){notify(error instanceof Error?error.message:'Collection update failed');}};
  const total=items.reduce((sum,item)=>sum+Number(item.amount||0),0);const digital=items.filter(x=>x.method!=='Cash').reduce((sum,item)=>sum+Number(item.amount||0),0);const cash=items.filter(x=>x.method==='Cash').reduce((sum,item)=>sum+Number(item.amount||0),0);
  return <><PageHead eyebrow="Repayments" title="Collections" subtitle="Cash, UPI and bank transfers recorded by the team." action={<Button onClick={()=>open('payment')} className="h-10 rounded-xl"><Plus/> Record payment</Button>}/><div className="grid gap-4 sm:grid-cols-3"><Metric icon={HandCoins} label="Collected" value={money(total)} note={items.length+' receipts'} positive/><Metric icon={Smartphone} label="Digital" value={money(digital)} note="UPI and bank transfers"/><Metric icon={CircleDollarSign} label="Cash collected" value={money(cash)} note="Cash receipts" warning/></div><Card className="mt-6 overflow-x-auto"><div className="grid min-w-[760px] grid-cols-[.8fr_1.3fr_1fr_1fr_1.2fr_.9fr] bg-[#f7faf8] px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-[#7f9189]">{['Receipt','Customer','Amount','Method','Collected by','Date'].map(x=><span key={x}>{x}</span>)}</div>{items.map(p=><div key={p.id} className="grid min-w-[760px] grid-cols-[.8fr_1.3fr_1fr_1fr_1.2fr_.9fr] items-center border-t border-[#edf1ef] px-5 py-4 text-sm hover:bg-[#f8fbf9]"><button onClick={()=>openReceipt(p)} className="text-left font-bold text-[#155d43] hover:underline">{p.id}</button><span>{p.customer_name}</span><b>{money(p.amount)}</b><span>{p.method}</span><span>{p.agent_name}</span><span>{new Date(p.collected_at*1000).toLocaleDateString()}</span></div>)}</Card>
  <Dialog open={Boolean(selected)} onOpenChange={(value)=>{if(!value){setSelected(null);setEditing(false)}}}><DialogContent className="sm:max-w-xl">{selected&&<><DialogHeader><div className="flex items-start justify-between gap-4 pr-8"><div><DialogTitle>{'Receipt '+selected.id}</DialogTitle><DialogDescription>Collection details and linked loan posting.</DialogDescription></div><Button onClick={()=>setEditing(!editing)} variant="outline" size="sm"><Pencil/> {editing?'Cancel':'Edit'}</Button></div></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Detail label="Customer" value={selected.customer_name}/><Detail label="Loan" value={selected.loan_id}/>{editing?<><Field label="Amount"><Input type="number" value={amount} onChange={(e)=>setAmount(e.target.value)}/></Field><Field label="Method"><select value={method} onChange={(e)=>setMethod(e.target.value)} className="h-8 rounded-lg border border-input bg-white px-2.5 text-sm"><option>Cash</option><option>UPI</option><option>Bank transfer</option></select></Field><Field label="Remarks" wide><Textarea value={remarks} onChange={(e)=>setRemarks(e.target.value)}/></Field><Field label="Replace proof (optional)" wide><Input type="file" accept="image/*,.pdf"/></Field></>:<><Detail label="Amount received" value={money(selected.amount)}/><Detail label="Payment method" value={selected.method}/><Detail label="Collected by" value={selected.agent_name}/><Detail label="Date" value={new Date(selected.collected_at*1000).toLocaleString()}/><Detail label="Remarks" value={selected.remarks||'—'} wide/></>}</div><div className="mt-2 flex items-center gap-3 rounded-xl bg-[#eef6f1] p-3"><FileCheck2 className="size-5 text-[#24704f]"/><div><b className="text-sm">{selected.proof_file_key||'No proof attached'}</b><p className="text-xs text-[#71857c]">{selected.proof_file_key?'Attached proof recorded':'Optional proof was not provided'}</p></div></div><DialogFooter>{editing&&<Button onClick={save}>Save collection</Button>}<Button variant="outline" onClick={()=>setSelected(null)}>Close</Button></DialogFooter></>}</DialogContent></Dialog></>;
}
function AgentSection({notify,manageAgent}:{notify:(message:string)=>void;manageAgent:(name:string)=>void}) {
  const [agents,setAgents]=useState<string[][]>([]);const [selected,setSelected]=useState<number|null>(null);const [adding,setAdding]=useState(false);const [deleteTarget,setDeleteTarget]=useState<string[]|null>(null);const [name,setName]=useState('');const [phone,setPhone]=useState('');
  const load=async()=>{try{const data=await getData();setAgents(data.agents.map((a:any)=>[a.name,String(a.assigned),money(a.collected),'—',a.phone,a.id,a.email||'']));}catch(error){notify(error instanceof Error?error.message:'Agent loading failed');}};
  useEffect(()=>{load();const refresh=()=>load();window.addEventListener('fundflow-data',refresh);return()=>window.removeEventListener('fundflow-data',refresh);},[]);
  const saveAgent=async()=>{if(!name.trim())return;try{if(adding){await postData({action:'create_agent',name:name.trim(),phone:phone.trim(),email:''});notify(name+' added as collection agent');}else if(selected!==null){await postData({action:'update_agent',id:agents[selected][5],name:name.trim(),phone:phone.trim(),email:agents[selected][6]||''});notify('Agent profile updated');}await load();refreshData();setAdding(false);setSelected(null);setName('');setPhone('');}catch(error){notify(error instanceof Error?error.message:'Agent save failed');}};
  const deleteAgent=async()=>{if(!deleteTarget)return;try{await postData({action:'delete_agent',id:deleteTarget[5]});setDeleteTarget(null);await load();refreshData();notify(deleteTarget[0]+' deleted');}catch(error){notify(error instanceof Error?error.message:'Agent deletion failed');}};
  const edit=(i:number)=>{setSelected(i);setName(agents[i][0]);setPhone(agents[i][4]);};
  return <><PageHead eyebrow="Role access" title="Collection agents" subtitle="Light-admin accounts see assigned customers in read-only mode." action={<Button onClick={()=>{setAdding(true);setName('');setPhone('')}} className="h-10 rounded-xl"><Plus/> Add agent</Button>}/><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{agents.map((a,i)=><Card key={a[5]||a[0]} className="p-5"><button onClick={()=>edit(i)} className="flex w-full items-center gap-3 text-left"><div className="grid size-11 place-items-center rounded-full bg-[#e4f3eb] font-bold text-[#1e6a4c]">{a[0].split(' ').map(x=>x[0]).join('')}</div><div><b>{a[0]}</b><p className="text-xs text-[#7b8d85]">Collection Agent · Active</p></div><Pencil className="ml-auto size-4 text-[#71857d]"/></button><div className="mt-5 grid grid-cols-3 gap-2 rounded-xl bg-[#f5f8f6] p-3 text-center"><div><b>{a[1]}</b><p className="text-[10px] text-[#7a8d85]">Assigned</p></div><div><b>{a[2]}</b><p className="text-[10px] text-[#7a8d85]">Collected</p></div><div><b>{a[3]}</b><p className="text-[10px] text-[#7a8d85]">Efficiency</p></div></div><div className="mt-4 flex gap-2"><Button onClick={()=>manageAgent(a[0])} variant="outline" className="flex-1">Manage access</Button><Button onClick={()=>setDeleteTarget(a)} variant="outline" size="icon" aria-label={'Delete '+a[0]} className="text-[#bd503c]"><Trash2/></Button></div></Card>)}</div>
  <Dialog open={adding||selected!==null} onOpenChange={(value)=>{if(!value){setAdding(false);setSelected(null)}}}><DialogContent><DialogHeader><DialogTitle>{adding?'Add collection agent':'Agent details'}</DialogTitle><DialogDescription>{adding?'Create a light-admin collection account.':'Edit the agent profile; use Manage Access for permissions.'}</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="Full name"><Input value={name} onChange={(e)=>setName(e.target.value)}/></Field><Field label="Mobile number"><Input value={phone} onChange={(e)=>setPhone(e.target.value)} placeholder="+91 98765 43210"/></Field><Field label="Assigned zone"><Select options={['Zone 1','Zone 2','Zone 3','Zone 4']}/></Field>{selected!==null&&<div className="grid grid-cols-2 gap-2 rounded-xl bg-[#f4f8f6] p-3 text-center text-sm"><div><b>{agents[selected][1]}</b><p className="text-xs text-[#72857d]">Customers</p></div><div><b>{agents[selected][2]}</b><p className="text-xs text-[#72857d]">Collected</p></div></div>}</div><DialogFooter><Button variant="outline" onClick={()=>{setAdding(false);setSelected(null)}}>Cancel</Button><Button disabled={!name.trim()} onClick={saveAgent}>{adding?'Create agent':'Save agent'}</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(deleteTarget)} onOpenChange={(value)=>!value&&setDeleteTarget(null)}><DialogContent><DialogHeader><DialogTitle>Delete collection agent?</DialogTitle><DialogDescription>{deleteTarget?deleteTarget[0]:''} will lose active access and disappear from the agent list.</DialogDescription></DialogHeader><div className="rounded-xl bg-[#fff0ed] p-3 text-xs text-[#9a4635]">Assigned customers will become unassigned. Historical receipts keep the agent name for the financial audit trail.</div><DialogFooter><Button variant="outline" onClick={()=>setDeleteTarget(null)}>Cancel</Button><Button variant="destructive" onClick={deleteAgent}><Trash2/> Delete agent</Button></DialogFooter></DialogContent></Dialog></>;
}
function Detail({label,value,wide}:{label:string;value:string;wide?:boolean}) { return <div className={'rounded-xl bg-[#f5f8f6] p-3 '+(wide?'sm:col-span-2':'')}><p className="text-[10px] font-bold uppercase tracking-wider text-[#73867e]">{label}</p><p className="mt-1 text-sm font-semibold text-[#243d33]">{value}</p></div> }
function downloadCsv(filename:string,content:string) { const url=URL.createObjectURL(new Blob([content],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download=filename;link.click();URL.revokeObjectURL(url); }
function CustomerSection({open,notify,assignments,assignCustomer}:{open:(m:Modal)=>void;notify:(m:string)=>void;assignments:Record<string,string>;assignCustomer:(name:string,id?:string)=>void}) {
  const [rows,setRows] = useState<string[][]>(customers);
  const [selected,setSelected] = useState<string[]>([]);
  const [editing,setEditing] = useState<string[]|null>(null);
  const [deleteNames,setDeleteNames] = useState<string[]>([]);
  const [editName,setEditName] = useState('');
  const [editPhone,setEditPhone] = useState('');
  const [loading,setLoading] = useState(true);
  const load=async()=>{try{const data=await getData();setRows(data.customers.map((c:any)=>[c.name,c.phone,String(c.active_loans),money(c.outstanding),c.agent_name||'Unassigned',c.kyc||'Review',c.id,c.email||'']));}catch(error){notify(error instanceof Error?error.message:'Could not load customers');}finally{setLoading(false);}};
  useEffect(()=>{load();const refresh=()=>load();window.addEventListener('fundflow-data',refresh);return()=>window.removeEventListener('fundflow-data',refresh);},[]);
  const toggle=(name:string)=>setSelected((current)=>current.includes(name)?current.filter(x=>x!==name):[...current,name]);
  const exportRows=()=>downloadCsv('fundflow-customers.csv','Customer,Phone,Active Loans,Outstanding,Assigned Agent,KYC\n'+rows.map(r=>r.slice(0,6).map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n'));
  const template=()=>downloadCsv('fundflow-customer-import-template.csv','Customer,Phone,Email,Assigned Agent\nSample Customer,+91 90000 00000,sample@example.com,Deepak Singh');
  const confirmDelete=async()=>{try{const ids=rows.filter(r=>deleteNames.includes(r[0])).map(r=>r[6]).filter(Boolean);await postData({action:'delete_customers',ids});await load();setSelected([]);notify('Delete completed. Customers with active loans were retained for ledger safety.');setDeleteNames([]);}catch(error){notify(error instanceof Error?error.message:'Delete failed');}};
  const startEdit=(row:string[])=>{setEditing(row);setEditName(row[0]);setEditPhone(row[1]);};
  const saveEdit=async()=>{if(!editing)return;try{await postData({action:'update_customer',id:editing[6],name:editName.trim(),phone:editPhone.trim(),email:editing[7]||''});await load();notify('Customer details updated');setEditing(null);}catch(error){notify(error instanceof Error?error.message:'Update failed');}};
  const importFile=async(file?:File)=>{if(!file)return;const text=await file.text();const imported=text.split(/\r?\n/).slice(1).filter(Boolean).map(line=>line.split(',').map(value=>value.trim().replace(/^"|"$/g,''))).filter(row=>row[0]&&row[1]);if(!imported.length){notify('No valid customer rows found');return;}try{for(const row of imported){await postData({action:'create_customer',name:row[0],phone:row[1],email:row[2]||'',agent_id:agentIdByName[row[3]]||'agent-deepak'});}await load();notify(file.name+' imported · '+imported.length+' customers added');}catch(error){notify(error instanceof Error?error.message:'Import failed');}};
  return <><PageHead eyebrow="Borrower management" title="Customers" subtitle="Create, edit, assign, import, export and manage customer records." action={<Button onClick={()=>open('customer')} className="h-10 rounded-xl"><Plus/> Create customer</Button>}/>
    <div className="mb-4 flex flex-wrap items-center gap-2"><Button onClick={template} variant="outline"><Download/> Sample template</Button><label className="inline-flex h-8 cursor-pointer items-center gap-1.5 rounded-lg border border-[#d7e2dd] bg-white px-2.5 text-sm font-medium hover:bg-[#f2f6f4]"><Upload className="size-4"/> Bulk import<input type="file" accept=".csv" className="hidden" onChange={(e)=>importFile(e.target.files?.[0])}/></label><Button onClick={exportRows} variant="outline"><Download/> Export</Button>{selected.length>0&&<div className="ml-auto flex items-center gap-2 rounded-xl bg-[#fff0ed] px-3 py-1.5 text-sm"><b>{selected.length} selected</b><Button onClick={()=>setDeleteNames(selected)} variant="destructive" size="sm"><Trash2/> Delete selected</Button></div>}</div>
    <Card className="overflow-x-auto"><div className="min-w-[900px]"><div className="grid grid-cols-[42px_1.4fr_.65fr_1fr_1fr_.7fr_190px] items-center bg-[#f7faf8] px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-[#7f9189]"><input aria-label="Select all customers" type="checkbox" checked={selected.length===rows.length&&rows.length>0} onChange={(e)=>setSelected(e.target.checked?rows.map(r=>r[0]):[])}/><span>Customer</span><span>Active loans</span><span>Outstanding</span><span>Assigned agent</span><span>KYC</span><span className="text-center">Actions</span></div>{rows.map(c=><div key={c[6]||c[0]} className="grid grid-cols-[42px_1.4fr_.65fr_1fr_1fr_.7fr_190px] items-center border-t border-[#edf1ef] px-5 py-4 text-sm"><input aria-label={'Select '+c[0]} type="checkbox" checked={selected.includes(c[0])} onChange={()=>toggle(c[0])}/><div><p className="font-bold">{c[0]}</p><p className="text-xs text-[#7c8e86]">{c[1]}</p></div><span>{c[2]}</span><b>{c[3]}</b><span className="font-medium">{assignments[c[0]]||c[4]}</span><span className={'status w-fit '+(c[5]==='Verified'?'status-green':'status-amber')}>{c[5]}</span><div className="flex items-center justify-end gap-1"><Button onClick={()=>assignCustomer(c[0],c[6])} variant="outline" size="sm">Assign</Button><Button onClick={()=>startEdit(c)} variant="ghost" size="icon-sm" aria-label={'Edit '+c[0]}><Pencil/></Button><Button onClick={()=>setDeleteNames([c[0]])} variant="ghost" size="icon-sm" aria-label={'Delete '+c[0]} className="text-[#bd503c]"><Trash2/></Button></div></div>)}</div>{loading&&<div className="p-10 text-center text-sm text-[#72857d]">Loading customers...</div>}{!loading&&rows.length===0&&<div className="p-10 text-center text-sm text-[#72857d]">No customers found. Import a file or create a customer.</div>}</Card>
    <Dialog open={Boolean(editing)} onOpenChange={(v)=>!v&&setEditing(null)}><DialogContent><DialogHeader><DialogTitle>Edit customer</DialogTitle><DialogDescription>Update contact information for this borrower.</DialogDescription></DialogHeader><div className="grid gap-4"><Field label="Full name"><Input value={editName} onChange={(e)=>setEditName(e.target.value)}/></Field><Field label="Mobile number"><Input value={editPhone} onChange={(e)=>setEditPhone(e.target.value)}/></Field><Field label="KYC status"><Select options={['Verified','Review','Pending']}/></Field></div><DialogFooter><Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button><Button onClick={saveEdit}>Save customer</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={deleteNames.length>0} onOpenChange={(v)=>!v&&setDeleteNames([])}><DialogContent><DialogHeader><DialogTitle>Delete {deleteNames.length===1?'customer':'customers'}?</DialogTitle><DialogDescription>This removes customers without loan history. Ledger-linked borrowers are retained.</DialogDescription></DialogHeader><div className="rounded-xl bg-[#fff0ed] p-3 text-xs text-[#9a4635]">Customers with active or historical loans cannot be permanently deleted.</div><DialogFooter><Button variant="outline" onClick={()=>setDeleteNames([])}>Cancel</Button><Button variant="destructive" onClick={confirmDelete}><Trash2/> Delete</Button></DialogFooter></DialogContent></Dialog>
  </>;
}
function ReminderDialog({channel,close,finish}:{channel:'SMS'|'WhatsApp';close:()=>void;finish:(message:string)=>void}) {
  const [scope,setScope]=useState('All 12 due today');
  const [schedule,setSchedule]=useState('Send now');
  const [message,setMessage]=useState('Hello {customer}, your repayment of {amount} for loan {loan_id} is due today. Please pay or contact your collection agent.');
  return <Dialog open onOpenChange={(v)=>!v&&close()}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Send {channel} reminders</DialogTitle><DialogDescription>Review recipients, delivery timing and the customer message.</DialogDescription></DialogHeader><div className="grid gap-4 py-2"><Field label="Recipients"><select value={scope} onChange={(e)=>setScope(e.target.value)} className="h-9 rounded-lg border border-input bg-white px-2.5 text-sm"><option>All 12 due today</option><option>8 pending customers only</option><option>Overdue customers only</option><option>Single customer</option></select></Field><Field label="Delivery"><select value={schedule} onChange={(e)=>setSchedule(e.target.value)} className="h-9 rounded-lg border border-input bg-white px-2.5 text-sm"><option>Send now</option><option>Schedule for 6:00 PM</option><option>Tomorrow at 9:00 AM</option></select></Field><Field label="Message"><Textarea rows={5} value={message} onChange={(e)=>setMessage(e.target.value)}/></Field><div className="rounded-xl border border-[#dbe5e0] bg-[#f7faf8] p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[#70837b]">Preview</p><p className="mt-2 text-sm text-[#365348]">{message.replace('{customer}','Arjun').replace('{amount}','₹12,500').replace('{loan_id}','LN-2048')}</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked className="size-4 accent-[#1d6c4d]"/> Record each delivery in the customer activity log</label></div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button disabled={!message.trim()} onClick={()=>finish(channel+' reminder job created for '+scope.toLowerCase())}>{schedule==='Send now'?'Send reminders':'Schedule reminders'}</Button></DialogFooter></DialogContent></Dialog>;
}

function TopupDecisionDialog({decision,close,finish}:{decision:'approve'|'decline';close:()=>void;finish:(message:string)=>void}) {
  const [remarks,setRemarks]=useState('');
  const approve=decision==='approve';
  return <Dialog open onOpenChange={(v)=>!v&&close()}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>{approve?'Approve':'Decline'} top-up request</DialogTitle><DialogDescription>Arjun Mehta requested ₹50,000 against the existing property security.</DialogDescription></DialogHeader><div className="grid gap-4 py-2 sm:grid-cols-2">{approve?<><Field label="Approved amount"><Input type="number" defaultValue="50000"/></Field><Field label="Interest type"><Select options={['Fixed','Floating']}/></Field><Field label="Annual interest rate"><Input type="number" defaultValue="16"/></Field><Field label="Disbursement date"><Input type="date" defaultValue="2026-09-05"/></Field><label className="sm:col-span-2 flex items-center gap-2 rounded-xl bg-[#eef6f1] p-3 text-sm"><input type="checkbox" defaultChecked className="size-4 accent-[#1d6c4d]"/> Existing property security has been re-verified</label></>:<Field label="Decline reason" wide><Select options={['Insufficient security value','Repayment history','Incomplete documents','Other']}/></Field>}<Field label={approve?'Approval remarks':'Mandatory decline remarks'} wide><Textarea value={remarks} onChange={(e)=>setRemarks(e.target.value)} placeholder={approve?'Conditions or internal approval note':'Explain why this request is declined'}/></Field></div><div className="rounded-xl bg-[#f5f8f6] p-3 text-xs text-[#5e756b]">{approve?'Approval adds ₹50,000 to the customer principal, recalculates the schedule, and records an audit entry.':'The customer will be notified and the decision will remain in the audit history.'}</div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button variant={approve?'default':'destructive'} disabled={!approve&&!remarks.trim()} onClick={()=>finish(approve?'Top-up approved · loan schedule updated':'Top-up declined · customer notified')}>{approve?'Approve & update loan':'Decline request'}</Button></DialogFooter></DialogContent></Dialog>;
}
function TableHead({labels}:{labels:string[]}) { return <div className="grid min-w-[700px] grid-flow-col auto-cols-fr bg-[#f7faf8] px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-[#7f9189]">{labels.map((x,i)=><span key={`${x}-${i}`}>{x}</span>)}</div> }

function RolePortal({role,active,period,setPeriod,open,notify}:{role:Role;active:string;period:string;setPeriod:(v:string)=>void;open:(m:Modal)=>void;notify:(m:string)=>void}) {
  if(role==='customer') return <><PageHead eyebrow="Customer portal" title="Welcome back, Arjun" subtitle="Your loan balance, repayments and approved account details." action={<Button onClick={()=>open('topup')} className="h-10 rounded-xl"><Plus/> Request top-up</Button>}/><div className="grid gap-4 sm:grid-cols-3"><Metric icon={WalletCards} label="Amount borrowed" value="₹2,50,000" note="Given 12 Mar 2026"/><Metric icon={HandCoins} label="Amount settled" value="₹67,600" note="27% repaid" positive/><Metric icon={CalendarDays} label="Balance to settle" value="₹1,82,400" note="₹12,500 due today" warning/></div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.8fr]"><Card className="p-5"><div className="flex justify-between"><div><b>Repayment schedule</b><p className="text-xs text-[#7d8f87]">Weekly · Fixed interest 16%</p></div><Period value={period} onChange={setPeriod}/></div><div className="mt-5 space-y-3">{[['Today','₹12,500','Due now'],['11 Sep 2026','₹12,500','Upcoming'],['18 Sep 2026','₹12,500','Upcoming'],['25 Sep 2026','₹12,500','Upcoming']].map((r,i)=><div key={r[0]} className="flex items-center rounded-xl border border-[#e3ebe7] p-3"><div className={`mr-3 grid size-9 place-items-center rounded-xl ${i===0?'bg-[#fff0d6] text-[#95610a]':'bg-[#edf4f1] text-[#6f837b]'}`}><CalendarDays className="size-4"/></div><div><b className="text-sm">{r[0]}</b><p className="text-xs text-[#7a8d85]">{r[2]}</p></div><b className="ml-auto">{r[1]}</b></div>)}</div></Card><div className="space-y-5"><Card className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[#73867e]">Loan security</p><div className="mt-4 flex items-center gap-3 rounded-xl bg-[#f2f7f4] p-3"><FileCheck2 className="size-5 text-[#2b7b59]"/><div><b className="text-sm">Property deed</b><p className="text-xs text-[#7a8c84]">Verified by admin</p></div></div></Card><Card className="p-5"><b>Need help?</b><p className="mt-1 text-xs text-[#768981]">Contact your assigned agent, Deepak Singh.</p><Button onClick={()=>notify('WhatsApp chat opened')} variant="outline" className="mt-4 w-full"><MessageCircle/> WhatsApp agent</Button></Card></div></div></>;
  return <><PageHead eyebrow="Collection route · Zone 3" title="Good morning, Deepak" subtitle="You can collect payments and view only customers assigned to you." action={<Button onClick={()=>open('payment')} className="h-10 rounded-xl"><Plus/> Record collection</Button>}/><div className="grid gap-4 sm:grid-cols-3"><Metric icon={UsersRound} label="Assigned today" value="18" note="6 completed"/><Metric icon={HandCoins} label="Collected" value="₹92,600" note="86% of target" positive/><Metric icon={Clock3} label="Pending" value="₹15,400" note="12 visits left" warning/></div><Card className="mt-6 overflow-hidden"><div className="flex items-center justify-between px-5 py-4"><div><b>Assigned customers</b><p className="text-xs text-[#7b8d85]">Customer details are read-only</p></div><span className="status status-green">Route active</span></div>{[['Arjun Mehta','₹12,500','Due today','Sector 18'],['Ravi Kumar','₹18,000','Overdue 2 days','Model Town'],['Sunita Rao','₹7,500','Due today','Civil Lines']].map((r,i)=><div key={r[0]} className="flex flex-wrap items-center gap-4 border-t border-[#edf1ef] px-5 py-4 text-sm"><div className="grid size-9 place-items-center rounded-full bg-[#e8f4ed] font-bold text-[#28644c]">{r[0].split(' ').map(x=>x[0]).join('')}</div><div className="min-w-[150px]"><b>{r[0]}</b><p className="text-xs text-[#7c8e86]">{r[3]}</p></div><b className="sm:ml-auto">{r[1]}</b><span className={`status ${i===1?'status-red':'status-amber'}`}>{r[2]}</span><Button onClick={()=>open('payment')} size="sm">Collect</Button><button onClick={()=>open('exception')} className="text-xs font-bold text-[#af5b46]">Exception</button></div>)}</Card><p className="mt-3 flex items-center gap-2 text-xs text-[#73867d]"><ShieldCheck className="size-4"/> Role restriction active: editing customer or loan details is disabled.</p></>;
}

function ActionDialog({modal,close,finish}:{modal:Modal;close:()=>void;finish:(m:string)=>void}) {
  const titles = {loan:'Create new loan',customer:'Create customer',payment:'Record collection',topup:'Request a top-up',exception:'Emergency exception'};
  const [customerName,setCustomerName]=useState('');const [customerPhone,setCustomerPhone]=useState('');const [customerEmail,setCustomerEmail]=useState('');const [customerAgent,setCustomerAgent]=useState('Deepak Singh');
  const [database,setDatabase]=useState<any>({customers:[],loans:[]});const [recordCustomerId,setRecordCustomerId]=useState('');const [recordLoanId,setRecordLoanId]=useState('');
  const [principal,setPrincipal]=useState('');const [givenDate,setGivenDate]=useState('2026-09-05');const [dueDate,setDueDate]=useState('');const [interestType,setInterestType]=useState('Fixed');const [interestRate,setInterestRate]=useState('16');const [frequency,setFrequency]=useState('Monthly');const [securityType,setSecurityType]=useState('Asset');const [securityFile,setSecurityFile]=useState('');const [remarks,setRemarks]=useState('');
  const [paymentAmount,setPaymentAmount]=useState('');const [paymentMethod,setPaymentMethod]=useState('UPI');const [saving,setSaving]=useState(false);const [formError,setFormError]=useState('');
  useEffect(()=>{if(modal!=='loan'&&modal!=='payment')return;getData().then(data=>{setDatabase(data);if(!recordCustomerId&&data.customers[0])setRecordCustomerId(data.customers[0].id);if(!recordLoanId&&data.loans[0])setRecordLoanId(data.loans[0].id);}).catch(error=>setFormError(error.message));},[modal]);
  if(!modal) return null;
  const submit=async()=>{
    if(modal==='topup'||modal==='exception'){finish(modal==='topup'?'Top-up request sent for approval':'Exception saved with remarks');return;}
    setSaving(true);setFormError('');
    try{
      if(modal==='customer'){
        if(!customerName.trim()||!customerPhone.trim())throw new Error('Full name and mobile number are required.');
        await postData({action:'create_customer',name:customerName.trim(),phone:customerPhone.trim(),email:customerEmail.trim(),agent_id:agentIdByName[customerAgent]||'agent-deepak'});
        refreshData();finish('Customer created and assigned');return;
      }
      if(modal==='loan'){
        if(!recordCustomerId||Number(principal)<=0||!dueDate)throw new Error('Customer, principal and first due date are required.');
        await postData({action:'create_loan',customer_id:recordCustomerId,principal:Number(principal),given_date:givenDate,next_due_date:dueDate,interest_type:interestType.toLowerCase(),interest_rate:Number(interestRate),repayment_frequency:frequency.toLowerCase(),security_type:securityType.toLowerCase(),security_file_key:securityFile,remarks});
        refreshData();finish('Loan created and reminders scheduled');return;
      }
      if(modal==='payment'){
        if(!recordLoanId||Number(paymentAmount)<=0)throw new Error('Loan and a valid collection amount are required.');
        await postData({action:'create_collection',loan_id:recordLoanId,agent_id:'agent-deepak',amount:Number(paymentAmount),method:paymentMethod,remarks});
        refreshData();finish('Payment recorded; balance updated');
      }
    }catch(error){setFormError(error instanceof Error?error.message:'Save failed');setSaving(false);}
  };
  return <Dialog open onOpenChange={(v)=>!v&&close()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{titles[modal as keyof typeof titles]}</DialogTitle><DialogDescription>{modal==='loan'?'Set principal, security, interest and repayment terms.':modal==='payment'?'Log a customer payment with optional proof.':modal==='topup'?'Your request will require super-admin approval.':modal==='exception'?'Record the emergency reason and revised mandatory due date.':'Create a borrower account and assign a collection agent.'}</DialogDescription></DialogHeader><div className="grid gap-4 py-2 sm:grid-cols-2">
    {modal==='customer' && <><Field label="Full name"><Input value={customerName} onChange={(e)=>setCustomerName(e.target.value)} placeholder="Customer name"/></Field><Field label="Mobile number"><Input value={customerPhone} onChange={(e)=>setCustomerPhone(e.target.value)} placeholder="+91 98765 43210"/></Field><Field label="Email"><Input value={customerEmail} onChange={(e)=>setCustomerEmail(e.target.value)} type="email" placeholder="name@example.com"/></Field><Field label="Assign agent"><select value={customerAgent} onChange={(e)=>setCustomerAgent(e.target.value)} className="h-8 w-full rounded-lg border border-input bg-white px-2.5 text-sm font-normal outline-none"><option>Deepak Singh</option><option>Meera Joshi</option><option>Akash Verma</option></select></Field><Field label="Address" wide><Textarea placeholder="Residential address"/></Field></>}
    {modal==='loan' && <><Field label="Customer"><select value={recordCustomerId} onChange={(e)=>setRecordCustomerId(e.target.value)} className="h-8 rounded-lg border border-input bg-white px-2.5 text-sm">{database.customers.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Principal amount"><Input value={principal} onChange={(e)=>setPrincipal(e.target.value)} type="number" placeholder="250000"/></Field><Field label="Given date"><Input value={givenDate} onChange={(e)=>setGivenDate(e.target.value)} type="date"/></Field><Field label="First due date"><Input value={dueDate} onChange={(e)=>setDueDate(e.target.value)} type="date"/></Field><Field label="Interest type"><select value={interestType} onChange={(e)=>setInterestType(e.target.value)} className="h-8 rounded-lg border border-input bg-white px-2.5 text-sm"><option>Fixed</option><option>Floating</option></select></Field><Field label="Annual interest rate"><Input value={interestRate} onChange={(e)=>setInterestRate(e.target.value)} type="number"/></Field><Field label="Return basis"><select value={frequency} onChange={(e)=>setFrequency(e.target.value)} className="h-8 rounded-lg border border-input bg-white px-2.5 text-sm"><option>Daily</option><option>Weekly</option><option>Monthly</option><option>Yearly</option></select></Field><Field label="Security type"><select value={securityType} onChange={(e)=>setSecurityType(e.target.value)} className="h-8 rounded-lg border border-input bg-white px-2.5 text-sm"><option>Asset</option><option>Surety</option></select></Field><Field label="Asset / surety document" wide><Input type="file" accept="image/*,.pdf" onChange={(e)=>setSecurityFile(e.target.files?.[0]?.name||'')}/></Field><Field label="Remarks" wide><Textarea value={remarks} onChange={(e)=>setRemarks(e.target.value)} placeholder="Collateral details and notes"/></Field></>}
    {modal==='payment' && <><Field label="Customer / loan"><select value={recordLoanId} onChange={(e)=>setRecordLoanId(e.target.value)} className="h-8 rounded-lg border border-input bg-white px-2.5 text-sm">{database.loans.map((l:any)=><option key={l.id} value={l.id}>{l.customer_name+' · '+l.id+' · '+money(l.balance)}</option>)}</select></Field><Field label="Amount collected"><Input value={paymentAmount} onChange={(e)=>setPaymentAmount(e.target.value)} type="number" placeholder="12500"/></Field><Field label="Payment method"><select value={paymentMethod} onChange={(e)=>setPaymentMethod(e.target.value)} className="h-8 rounded-lg border border-input bg-white px-2.5 text-sm"><option>Cash</option><option>UPI</option><option>Bank transfer</option></select></Field><Field label="Collection date"><Input type="date" defaultValue="2026-09-05"/></Field><Field label="Payment proof (optional)" wide><Input type="file" accept="image/*,.pdf"/></Field><Field label="Remarks" wide><Textarea value={remarks} onChange={(e)=>setRemarks(e.target.value)} placeholder="Receipt or transaction notes"/></Field></>}
    {modal==='topup' && <><Field label="Requested amount"><Input type="number" placeholder="50000"/></Field><Field label="Preferred interest"><Select options={['Fixed','Floating']}/></Field><Field label="Security"><Select options={['Existing asset','New asset','Surety']}/></Field><Field label="Document"><Input type="file" accept="image/*,.pdf"/></Field><Field label="Reason" wide><Textarea placeholder="Reason for requesting a top-up"/></Field></>}
    {modal==='exception' && <><Field label="Revised due date"><Input type="date"/></Field><Field label="Emergency type"><Select options={['Medical','Family emergency','Natural disaster','Other']}/></Field><Field label="Mandatory remarks" wide><Textarea required placeholder="Explain the exceptional circumstances"/></Field></>}
  </div>{formError&&<div className="rounded-xl bg-[#fff0ed] p-3 text-xs font-semibold text-[#a24432]">{formError}</div>}<div className="rounded-xl bg-[#eef6f1] p-3 text-xs text-[#426557]">{modal==='loan'?'SMS and WhatsApp reminders will be scheduled before each mandatory due date.':modal==='customer'?'A portal account will be created; customers cannot self-register.':modal==='payment'?'Balance and reports update as soon as this receipt is saved.':modal==='topup'?'No funds are added until the super admin approves this request.':'The original due date remains in the audit history.'}</div><DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button disabled={saving} onClick={submit}>{saving?'Saving...':modal==='topup'?'Send request':'Save'}</Button></DialogFooter></DialogContent></Dialog>;
}function AdminToolDialog({modal,close,finish,selectedCustomer,selectedAgent,saveAssignment}:{modal:'settings'|'access'|'assignment';close:()=>void;finish:(m:string)=>void;selectedCustomer:string;selectedAgent:string;saveAssignment:(agent:string)=>void}) {
  const [agent, setAgent] = useState(selectedAgent || 'Deepak Singh');
  const [agentStatus, setAgentStatus] = useState('Active');
  const [smsEnabled, setSmsEnabled] = useState(true);
  const [whatsappEnabled, setWhatsappEnabled] = useState(true);
  const [logoFile,setLogoFile]=useState<File|null>(null);
  const [faviconFile,setFaviconFile]=useState<File|null>(null);
  const [brandingSaving,setBrandingSaving]=useState(false);
  const [brandingError,setBrandingError]=useState('');
  const title = modal === 'settings' ? 'Application settings' : modal === 'access' ? 'Manage agent access' : 'Assign collection agent';
  const description = modal === 'settings' ? 'Configure lending defaults, customer reminders, logo and browser favicon.' : modal === 'access' ? 'Control the light-admin permissions for ' + selectedAgent + '.' : 'Assign ' + selectedCustomer + ' and the related active loan to a collection agent.';
  const save = async () => {
    if (modal === 'assignment') { saveAssignment(agent); return; }
    if(modal==='settings'&&(logoFile||faviconFile)){
      setBrandingSaving(true);setBrandingError('');
      try{
        const form=new FormData();if(logoFile)form.append('logo',logoFile);if(faviconFile)form.append('favicon',faviconFile);
        const response=await fetch('/api/branding',{method:'POST',body:form,signal:AbortSignal.timeout(15000)});
        if(!response.ok){throw new Error((await response.json()).error||'Branding upload failed');}
        window.dispatchEvent(new Event('fundflow-brand'));
      }catch(error){setBrandingError(error instanceof Error?error.message:'Branding upload failed');setBrandingSaving(false);return;}
    }
    finish(modal === 'settings' ? 'Application settings and branding saved' : selectedAgent + ' access updated');
  };
  return <Dialog open onOpenChange={(value)=>!value&&close()}><DialogContent className={modal === 'settings' ? 'max-h-[90vh] overflow-y-auto gap-3 sm:max-w-4xl' : 'sm:max-w-xl'}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></DialogHeader>
    {modal === 'settings' && <div className="grid gap-3 sm:grid-cols-2"><Field label="Business name"><Input defaultValue="FundFlow Finance"/></Field><Field label="Currency"><Select options={['INR (₹)','USD ($)','AED (د.إ)']}/></Field><Field label="Default fixed interest"><Input type="number" defaultValue="16"/></Field><Field label="Floating rate benchmark"><Select options={['RBI repo rate + margin','MCLR + margin','Manual index']}/></Field><Field label="Default grace period"><Select options={['No grace period','1 day','3 days','7 days']}/></Field><Field label="Reminder timing"><Select options={['3 days and 1 day before','1 day before','On due date']}/></Field><Field label="Site logo"><Input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(e)=>setLogoFile(e.target.files?.[0]||null)}/>{logoFile&&<span className="font-normal text-[#71857c]">{logoFile.name}</span>}</Field><Field label="Browser favicon"><Input type="file" accept="image/png,image/x-icon,image/vnd.microsoft.icon" onChange={(e)=>setFaviconFile(e.target.files?.[0]||null)}/>{faviconFile&&<span className="font-normal text-[#71857c]">{faviconFile.name}</span>}</Field>{brandingError&&<div className="sm:col-span-2 rounded-xl bg-[#fff0ed] p-3 text-xs font-semibold text-[#a24432]">{brandingError}</div>}<label className="flex items-center gap-3 rounded-xl border border-[#dbe5e0] p-3 text-sm font-semibold"><input type="checkbox" checked={smsEnabled} onChange={(e)=>setSmsEnabled(e.target.checked)} className="size-4"/> SMS reminders</label><label className="flex items-center gap-3 rounded-xl border border-[#dbe5e0] p-3 text-sm font-semibold"><input type="checkbox" checked={whatsappEnabled} onChange={(e)=>setWhatsappEnabled(e.target.checked)} className="size-4"/> WhatsApp reminders</label></div>}
    {modal === 'access' && <div className="py-2"><div className="mb-4 flex items-center gap-3 rounded-xl bg-[#eef6f1] p-4"><div className="grid size-10 place-items-center rounded-full bg-[#d8eddf] font-bold text-[#1e674b]">{selectedAgent.split(' ').map(x=>x[0]).join('')}</div><div><b>{selectedAgent}</b><p className="text-xs text-[#72877e]">Collection Agent · Light Admin</p></div><select value={agentStatus} onChange={(e)=>setAgentStatus(e.target.value)} className="ml-auto h-8 rounded-lg border border-[#ccdbd3] bg-white px-2 text-xs"><option>Active</option><option>Suspended</option></select></div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-[#6d8379]">Permissions</p><div className="space-y-2">{[['View assigned customers',true],['Record cash, UPI and bank payments',true],['Upload payment proof',true],['Request emergency exceptions',true],['Edit customer profile',false],['Create or modify loans',false]].map((item)=><label key={String(item[0])} className="flex items-center justify-between rounded-xl border border-[#e0e8e4] px-3 py-2.5 text-sm"><span>{item[0]}</span><input type="checkbox" defaultChecked={Boolean(item[1])} className="size-4 accent-[#1c6b4d]"/></label>)}</div></div>}
    {modal === 'assignment' && <div className="grid gap-4 py-2"><div className="rounded-xl bg-[#eef6f1] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#71877d]">Customer and loan</p><p className="mt-1 font-bold">{selectedCustomer}</p><p className="text-xs text-[#6d8279]">Active loan · Collection rights only</p></div><Field label="Collection agent"><select value={agent} onChange={(e)=>setAgent(e.target.value)} className="h-9 w-full rounded-lg border border-input bg-white px-2.5 text-sm outline-none"><option>Deepak Singh</option><option>Meera Joshi</option><option>Akash Verma</option></select></Field><Field label="Assignment remarks"><Textarea placeholder="Route, collection instructions or customer preference"/></Field><label className="flex items-center gap-3 text-sm"><input type="checkbox" defaultChecked className="size-4 accent-[#1c6b4d]"/> Notify the agent immediately</label></div>}
    <div className="rounded-xl bg-[#f5f8f6] p-3 text-xs text-[#5b7469]">{modal === 'assignment' ? 'The agent will see this customer in read-only mode and can record collections.' : modal === 'access' ? 'Customer and loan editing remain disabled unless explicitly enabled.' : 'Branding and reminder preferences apply across the application.'}</div>
    <DialogFooter><Button variant="outline" onClick={close}>Cancel</Button><Button disabled={brandingSaving} onClick={save}>{brandingSaving?'Uploading...':modal === 'assignment' ? 'Assign agent' : 'Save changes'}</Button></DialogFooter>
  </DialogContent></Dialog>;
}
function Field({label,children,wide}:{label:string;children:React.ReactNode;wide?:boolean}) { return <label className={`grid gap-1.5 text-xs font-bold text-[#526a60] ${wide?'sm:col-span-2':''}`}>{label}{children}</label> }
function Select({options}:{options:string[]}) { return <select className="h-8 w-full rounded-lg border border-input bg-white px-2.5 text-sm font-normal outline-none focus:border-[#2d8b63]">{options.map(x=><option key={x}>{x}</option>)}</select> }
