'use client';
import {useEffect,useState} from 'react';
import {permissionLabels,allowedPermissions,type Policy,type ManagedRole} from '@/lib/permissions';
export function AccessControl(){
 const [policy,setPolicy]=useState<Policy|null>(null),[managers,setManagers]=useState<{id:string;name:string;username:string;role:string}[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [editing,setEditing]=useState<{id:string;name:string;username:string;password:string}|null>(null),[deleting,setDeleting]=useState<{id:string;name:string}|null>(null);
 const [name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState('');
 const load=async()=>{try{const r=await fetch('/api/rbac',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setPolicy(d.policy);setManagers(d.managers)}catch(e){setMessage(e instanceof Error?e.message:'Could not load permissions')}};
 useEffect(()=>{void load()},[]);
 const save=async(body:unknown)=>{if(busy)return;setBusy(true);setMessage('');try{const r=await fetch('/api/rbac',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage('Saved. New permissions are enforced on the next API request.');setPassword('');setEditing(null);setDeleting(null);await load()}catch(e){setMessage(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}};
 return <div className="space-y-6"><h1 className="text-3xl font-bold">Access Control</h1><p className="text-sm text-[#6c8078]">Super Admin always retains full access. Agents remain restricted to assigned customers. Signed receipts and audit records remain immutable. Settings, account-role administration and receipt corrections are super-admin-only.</p>{message&&<p role="status" className="rounded-xl border bg-white p-3">{message}</p>}{!policy?<button onClick={load}>Retry loading permissions</button>:<><div className="grid gap-5 md:grid-cols-2">{(['manager','agent'] as ManagedRole[]).map(role=><fieldset disabled={busy} key={role} className="space-y-3 rounded-2xl border bg-white p-5"><legend className="px-2 font-bold">{role==='manager'?'Admin Manager':'Collection Agent'}</legend>{allowedPermissions[role].map(p=><label key={p} className="flex items-center gap-3 text-sm"><input type="checkbox" checked={policy[role].includes(p)} onChange={e=>setPolicy({...policy,[role]:e.target.checked?[...policy[role],p]:policy[role].filter(x=>x!==p)})}/>{permissionLabels[p]}</label>)}</fieldset>)}</div><p className="text-xs text-[#6c8078]">Create/edit permissions require their corresponding view permissions. Reports require customer, loan and collection views. Save will explain any missing dependencies.</p><button disabled={busy} onClick={()=>save({action:'policy',policy})} className="rounded-xl bg-[#153d30] px-5 py-3 text-white disabled:opacity-50">Save role permissions</button></>}
 {editing&&<section className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-bold">Edit Admin Manager</h2><form onSubmit={e=>{e.preventDefault();void save({action:'update_manager',...editing})}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-3"><label>Name<input required maxLength={100} value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} className="mt-1 w-full rounded border p-2"/></label><label>Username<input required minLength={3} maxLength={60} pattern="[a-zA-Z0-9._\-]+" autoComplete="off" value={editing.username} onChange={e=>setEditing({...editing,username:e.target.value})} className="mt-1 w-full rounded border p-2"/></label><label>New password (optional)<input type="password" minLength={10} maxLength={256} autoComplete="new-password" value={editing.password} onChange={e=>setEditing({...editing,password:e.target.value})} className="mt-1 w-full rounded border p-2"/><span className="text-xs">Leave blank to keep the current password.</span></label><button className="rounded-xl bg-[#153d30] p-3 text-white">Save manager</button><button type="button" className="rounded border p-3" onClick={()=>setEditing(null)}>Cancel</button></fieldset></form></section>}
 {deleting&&<section role="alert" className="space-y-3 rounded-2xl border border-red-200 bg-white p-5"><h2 className="font-bold">Delete {deleting.name}?</h2><p>The manager will lose access and be removed from this list. Financial records and audit history will be retained. This cannot be undone here.</p><button disabled={busy} onClick={()=>void save({action:'delete_manager',id:deleting.id})} className="mr-3 rounded bg-red-700 px-4 py-2 text-white">Confirm delete</button><button disabled={busy} onClick={()=>setDeleting(null)} className="rounded border px-4 py-2">Cancel</button></section>}
 <section className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-bold">Create Admin Manager</h2><form onSubmit={e=>{e.preventDefault();void save({action:'create_manager',name,username,password})}} className="grid gap-3 sm:grid-cols-3"><label>Name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label>Username<input required autoComplete="off" value={username} onChange={e=>setUsername(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><label>Password<input required minLength={10} maxLength={256} autoComplete="new-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1 w-full rounded border p-2"/></label><button disabled={busy} className="rounded-xl bg-[#153d30] p-3 text-white disabled:opacity-50">Create manager</button></form></section>
 <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Manager accounts</h2>{managers.map(m=><div key={m.id} className="mt-3 flex items-center justify-between gap-3 border-t pt-3"><span>{m.name} · {m.username} · {m.role==='manager'?'Active':'Disabled'}</span><div className="flex flex-wrap gap-2"><button disabled={busy} className="rounded border px-3 py-2" onClick={()=>{setDeleting(null);setEditing({id:m.id,name:m.name,username:m.username,password:''})}}>Edit</button><button disabled={busy} className="rounded border px-3 py-2 text-red-700" onClick={()=>{setEditing(null);setDeleting({id:m.id,name:m.name})}}>Delete</button><button disabled={busy} className="rounded border px-3 py-2" onClick={()=>save({action:'manager_status',id:m.id,enabled:m.role!=='manager'})}>{m.role==='manager'?'Disable':'Enable'}</button></div></div>)}{!managers.length&&<p className="mt-3 text-sm">No manager accounts yet.</p>}</section></div>;
}
