'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
type Row={id:string;status:string;created_at:number;name?:string;phone?:string;email?:string|null;occupation?:string;agent_name?:string;review_reason?:string|null};
export function CustomerApprovals({agent,canSubmit=true}:{agent:boolean;canSubmit?:boolean}){
 const [rows,setRows]=useState<Row[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState({name:'',phone:'',email:'',occupation:''}),[reasons,setReasons]=useState<Record<string,string>>({});
 const requestId=useRef('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/customer-requests?page='+page,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.requests);setMore(d.hasMore);setError('');window.dispatchEvent(new Event('fundflow-data'))}catch(e){setRows([]);setError(e instanceof Error?e.message:'Could not load requests')}},[page]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);const focus=()=>{void load();window.dispatchEvent(new Event('fundflow-data'))};window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus)}},[load]);
 async function send(body:Record<string,unknown>){if(busy)return;setBusy(true);setMessage('');setError('');try{const r=await fetch('/api/customer-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(body.action==='submit'?'Submitted for Admin Manager approval. Reference: '+d.request.id:body.action==='approve'?'Approved and assigned to the submitting agent.':'Request rejected. Customer access remains blocked.');if(body.action==='submit'){requestId.current='';setForm({name:'',phone:'',email:'',occupation:''});setOpen(false)}await load();window.dispatchEvent(new Event('fundflow-data'))}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 return <section className="mb-6 space-y-4 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{agent?'Customer request history':'Agent customer approvals'}</h2>{agent&&canSubmit&&<button disabled={busy} onClick={()=>setOpen(!open)} className="rounded-xl bg-[#153d30] px-4 py-2 text-white">{open?'Close form':'Create customer'}</button>}</div><p className="text-sm text-[#61786c]">{agent?'Create new customers together with a loan in the Loans section. Both are assigned to you after one Admin Manager approval. Until then, only your submission reference and status are visible.':'Review the submitted details. Approval creates the customer and assigns them to the submitting agent. Rejected submissions remain inaccessible to agents.'}</p>
 {agent&&canSubmit&&open&&<form onSubmit={e=>{e.preventDefault();requestId.current ||= crypto.randomUUID();void send({action:'submit',id:requestId.current,...form})}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2">{(['name','phone','occupation','email'] as const).map(field=><label className="text-sm capitalize" key={field}>{field}{field==='email'?' (optional)':' *'}<input required={field!=='email'} type={field==='email'?'email':field==='phone'?'tel':'text'} maxLength={field==='email'?254:field==='phone'?25:field==='occupation'?120:100} value={form[field]} onChange={e=>{requestId.current='';setForm({...form,[field]:e.target.value})}} className="mt-1 w-full rounded border p-2"/></label>)}<button className="rounded-xl bg-[#153d30] p-3 text-white">{busy?'Submitting…':'Submit for approval'}</button></fieldset></form>}
 {message&&<p role="status" className="rounded bg-green-50 p-3 text-sm">{message}</p>}{error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm">{error}</p>}
 <div className="flex gap-3 text-sm"><button disabled={busy} onClick={()=>void load()} className="underline">Refresh requests</button><button disabled={busy||page===0} onClick={()=>setPage(page-1)} className="disabled:opacity-40">Previous</button><span>Page {page+1}</span><button disabled={busy||!more} onClick={()=>setPage(page+1)} className="disabled:opacity-40">Next</button></div>
 {!rows.length&&!error&&<p className="text-sm">No submissions.</p>}{rows.map(r=><article key={r.id} className="space-y-2 rounded-xl border p-3 text-sm"><p className="break-all"><b>{r.status.toUpperCase()}</b> · Reference {r.id}</p><p>{new Date(r.created_at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>{!agent&&<><p><b>{r.name}</b> · {r.phone} · {r.email||'No email'}</p><p>Occupation: {r.occupation} · Submitted by: {r.agent_name}</p>{r.review_reason&&<p>Decision reason: {r.review_reason}</p>}{r.status==='pending'&&<div className="flex flex-wrap gap-2"><input aria-label={'Review reason for '+r.id} placeholder="Review reason (optional, up to 1,000 characters)" maxLength={1000} disabled={busy} value={reasons[r.id]||''} onChange={e=>setReasons({...reasons,[r.id]:e.target.value})} className="min-w-0 flex-1 rounded border p-2"/>{['approve','reject'].map(action=><button key={action} disabled={busy} onClick={()=>void send({action,id:r.id,reason:reasons[r.id]})} className="rounded border px-3 py-2 capitalize disabled:opacity-40">{action}</button>)}</div>}</>}</article>)}</section>;
}
