'use client';
import {useEffect,useState} from 'react';
import {dashboardTotals,type DashboardLoan,type DashboardReceipt} from '@/lib/dashboard';
export function Dashboard({name,period,setPeriod,navigate}:{name:string;period:string;setPeriod:(value:string)=>void;navigate:(value:string)=>void}) {
  const [data,setData]=useState<{loans:DashboardLoan[];collections:DashboardReceipt[]}|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  const [now,setNow]=useState(()=>new Date());
  useEffect(()=>{let active=true,version=0;const load=async()=>{const current=++version;try{const response=await fetch('/api/data',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('Could not load dashboard data. Please retry.');const result=await response.json();if(!Array.isArray(result.loans)||!Array.isArray(result.collections))throw new Error('Invalid dashboard response');if(active&&version===current){setData(result);setNow(new Date());setError('')}}catch(e){if(active&&version===current){setError(e instanceof Error?e.message:'Unable to load dashboard');setData(null)}}};void load();window.addEventListener('fundflow-data',load);window.addEventListener('focus',load);const timer=setInterval(()=>{if(!document.hidden)void load()},60000);return()=>{active=false;clearInterval(timer);window.removeEventListener('fundflow-data',load);window.removeEventListener('focus',load)}},[retry]);
  const money=(n:number)=>'₹'+n.toLocaleString('en-IN');
  const stats=data?dashboardTotals(data.loans,data.collections,period,now):null;
  return <>
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-[#6e857c]">{now.toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',weekday:'long',day:'numeric',month:'long',year:'numeric'})}</p><h1 className="mt-2 text-3xl font-bold">Welcome, {name.split(' ')[0]}</h1><p className="mt-2 text-sm text-[#6c8078]">Live lending and collection records · India time</p></div><div className="flex rounded-xl border bg-white p-1">{['Today','Week','Month'].map(value=><button key={value} aria-pressed={period===value} onClick={()=>setPeriod(value)} className={'rounded-lg px-4 py-2 text-sm font-semibold '+(value===period?'bg-[#153d30] text-white':'text-[#6c8078]')}>{value}</button>)}</div></div>
    <p className="mb-4 text-xs text-[#6c8078]">{stats?`${stats.start} to ${stats.today}`:''} · Week = last 7 calendar days; Month = month to date. Portfolio and overdue totals are current balances.</p>
    {error?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-5">{error}<button className="ml-4 underline" onClick={()=>setRetry(v=>v+1)}>Retry</button></div>:!stats?<p role="status">Loading live dashboard…</p>:<>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
        ['Active portfolio',money(stats.portfolio),`${stats.open.length} open loans · current outstanding`],
        ['Collected · '+period,money(stats.collected),`${stats.paid.length} posted receipts in period`],
        ['Disbursed · '+period,money(stats.disbursed),`${stats.issued.length} loans issued in period`],
        ['Overdue balance',money(stats.overdueBalance),`${stats.overdue.length} open loans past their next due date`]
      ].map(([title,value,note])=><div key={title} className="rounded-2xl border border-[#dbe5e0] bg-white p-5"><p className="text-sm text-[#6c8078]">{title}</p><p className="my-5 text-3xl font-bold">{value}</p><p className="text-xs text-[#6c8078]">{note}</p></div>)}</div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[2fr_1fr]"><div className="overflow-hidden rounded-2xl border border-[#dbe5e0] bg-white"><div className="flex justify-between p-5"><div><h2 className="font-bold">Loans issued · {period}</h2><p className="text-xs text-[#6c8078]">Latest 10 in the selected period</p></div><button onClick={()=>navigate('Loans')} className="text-sm text-[#176447]">View all loans</button></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-[#f7faf8] text-xs"><tr>{['Customer / loan','Principal','Balance','Next due','Status'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{stats.issued.slice(0,10).map(l=><tr key={l.id} className="border-t"><td className="p-3">{l.customer_name}<span className="block text-xs text-[#6c8078]">{l.id}</span></td><td className="p-3">{money(l.principal)}</td><td className="p-3">{money(l.balance)}</td><td className="p-3">{l.next_due_date||'—'}</td><td className="p-3">{['closed','foreclosed'].includes(l.status)?l.status:l.balance<=0?'Cleared':l.next_due_date&&l.next_due_date<stats.today?'Overdue':l.next_due_date===stats.today?'Due today':l.status}</td></tr>)}{!stats.issued.length&&<tr><td colSpan={5} className="p-6 text-center text-[#6c8078]">No loans issued in this period.</td></tr>}</tbody></table></div></div>
      <div className="rounded-2xl border border-[#dbe5e0] bg-white p-5"><h2 className="font-bold">Open loans due · {period}</h2><p className="mt-2 text-3xl font-bold">{stats.due.length}</p><p className="mt-2 text-sm text-[#6c8078]">Outstanding balance: {money(stats.due.reduce((sum,l)=>sum+Number(l.balance),0))}</p><p className="mt-3 text-xs text-[#6c8078]">Based on each loan’s next due date. This is the remaining loan balance, not an installment target.</p><button onClick={()=>navigate('Reminders')} className="mt-5 rounded-xl bg-[#153d30] px-4 py-2 text-sm text-white">Open reminders</button></div></div>
    </>}
  </>;
}
