'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {upfrontTerms} from '@/lib/upfront-loan';
import {LoanFinancialSummary} from './loan-financial-summary';
import type {LoanRequest} from '@/lib/loan-requests';
type Customer={id:string;name:string};
type ActiveLoan={loan_number?:string|null;interest_model?:string;interest_amount?:number;first_due_date?:string;total_repayable?:number;next_payment_date?:string|null;next_installment_due?:number;id:string;customer_name:string;principal:number;balance:number;interest_type:string;interest_rate:number;repayment_frequency:string;given_date:string;next_due_date:string;end_date:string;status:string;security_type:string;remarks:string|null};
const empty={loan_number:'',customer_id:'',principal:'',interest_rate:'',interest_type:'fixed',repayment_frequency:'daily',given_date:'',next_due_date:'',end_date:'',security_type:'asset',remarks:''};
const money=(n:number)=>'₹'+Number(n).toLocaleString('en-IN');
export function LoanApprovals({agent,canSubmit=true,canCreateCustomer=false}:{agent:boolean;canSubmit?:boolean;canCreateCustomer?:boolean}){
 const [customerMode,setCustomerMode]=useState(canCreateCustomer?'new':'existing');
 const [newCustomer,setNewCustomer]=useState({name:'',phone:'',email:'',occupation:''});
 const [rows,setRows]=useState<Partial<LoanRequest>[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[loans,setLoans]=useState<ActiveLoan[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[reasons,setReasons]=useState<Record<string,string>>({});
 const requestId=useRef('');
 useEffect(()=>{try{const t=upfrontTerms(form.given_date,form.repayment_frequency);setForm(f=>({...f,next_due_date:t.first_due_date,end_date:t.end_date}))}catch{}},[form.given_date,form.repayment_frequency]);
 const load=useCallback(async()=>{try{
   if(!agent||canSubmit){const r=await fetch('/api/loan-requests?page='+page,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.requests);setMore(d.hasMore);}
   if(agent){const r=await fetch('/api/data',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setCustomers(d.customers);setLoans(d.loans);}
   setError('');
 }catch(e){setRows([]);setCustomers([]);setLoans([]);setError(e instanceof Error?e.message:'Could not load loan requests')}},[page,agent,canSubmit]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);const refresh=()=>void load();window.addEventListener('focus',refresh);window.addEventListener('fundflow-data',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('fundflow-data',refresh)}},[load]);
 async function send(body:Record<string,unknown>){if(busy)return;setBusy(true);setMessage('');setError('');try{
   const r=await fetch('/api/loan-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);
   setMessage(body.action==='submit'?'Submitted for Admin Manager approval.':body.action==='approve'?'Loan approved for the submitting agent.':'Loan rejected. No active loan or balance was created.');
   if(body.action==='submit'){requestId.current='';setForm(empty);setNewCustomer({name:'',phone:'',email:'',occupation:''});setOpen(false)}await load();window.dispatchEvent(new Event('fundflow-data'));
 }catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 const change=(key:keyof typeof empty,value:string)=>{requestId.current='';setForm({...form,[key]:value})};
 return <div className="space-y-6"><section className="mb-6 space-y-4 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{agent?'Customers & loans':'Agent customer & loan approvals'}</h2>{agent&&canSubmit&&<button disabled={busy} onClick={()=>setOpen(!open)} className="rounded-xl bg-[#153d30] px-4 py-2 text-white">{open?'Close form':'Create customer / loan'}</button>}</div><p className="text-sm text-[#61786c]">{agent?'Submit a new customer and loan together for one approval, or a loan for an existing assigned customer. Pending loans show their submission date and status; details and collections unlock after approval.':'Review customer details and loan terms together, then approve or reject. Customer assignment and agent status are checked again at approval.'}</p>
 {agent&&canSubmit&&open&&<form onSubmit={e=>{e.preventDefault();requestId.current ||= crypto.randomUUID();void send({action:'submit',id:requestId.current,...form,customer_id:customerMode==='new'?'':form.customer_id,new_customer:customerMode==='new'?newCustomer:null,principal:Number(form.principal),interest_rate:Number(form.interest_rate)})}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
 <label className="text-sm">Customer type<select value={customerMode} onChange={e=>{setCustomerMode(e.target.value);requestId.current=''}} className="mt-1 w-full rounded border p-2">{canCreateCustomer&&<option value="new">Create new customer + loan</option>}<option value="existing">Existing assigned customer</option></select></label>
 {customerMode==='new'&&canCreateCustomer?<>{(['name','phone','occupation','email'] as const).map(field=><label key={field} className="text-sm capitalize">{field}{field==='email'?' (optional)':' *'}<input required={field!=='email'} type={field==='email'?'email':field==='phone'?'tel':'text'} maxLength={field==='email'?254:field==='phone'?25:field==='occupation'?120:100} value={newCustomer[field]} onChange={e=>{requestId.current='';setNewCustomer({...newCustomer,[field]:e.target.value})}} className="mt-1 w-full rounded border p-2"/></label>)}</>:<label className="text-sm">Assigned customer<select required value={form.customer_id} onChange={e=>change('customer_id',e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Choose approved customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
 <label className="text-sm">Loan number *<input required maxLength={40} pattern="[A-Za-z0-9][A-Za-z0-9\/_\-]{0,39}" value={form.loan_number} onChange={e=>change('loan_number',e.target.value.toUpperCase())} placeholder="Enter your loan number" className="mt-1 w-full rounded border p-2"/></label>
 <label className="text-sm">Loan amount (₹)<input required type="number" min="1" max="9007199254740991" step="1" value={form.principal} onChange={e=>change('principal',e.target.value)} className="mt-1 w-full rounded border p-2"/></label>
 <label className="text-sm">Upfront interest deducted (%)<input required type="number" min="0" step="any" value={form.interest_rate} onChange={e=>change('interest_rate',e.target.value)} className="mt-1 w-full rounded border p-2"/></label>
 {([{key:'interest_type',label:'Interest type',options:['fixed']},{key:'repayment_frequency',label:'Return basis',options:['daily','weekly','yearly']},{key:'security_type',label:'Security type',options:['asset','surety']}] as const).map(f=><label key={f.key} className="text-sm">{f.label}<select value={form[f.key]} onChange={e=>change(f.key,e.target.value)} className="mt-1 w-full rounded border p-2">{f.options.map(o=><option key={o}>{o}</option>)}</select></label>)}
 {([{key:'given_date',label:'Start date'},{key:'next_due_date',label:'First due date'},{key:'end_date',label:'End date'}] as const).map(f=><label key={f.key} className="text-sm">{f.label}<input required readOnly={f.key!=='given_date'} type="date" min={f.key==='given_date'?'1900-01-01':form.given_date||'1900-01-01'} max={f.key==='next_due_date'?form.end_date||undefined:undefined} value={form[f.key]} onChange={e=>change(f.key,e.target.value)} className="mt-1 w-full rounded border p-2"/></label>)}
 <label className="text-sm sm:col-span-2">Remarks (optional)<textarea maxLength={2000} value={form.remarks} onChange={e=>change('remarks',e.target.value)} className="mt-1 w-full rounded border p-2"/></label><button disabled={customerMode==='existing'&&!customers.length} className="self-end rounded-xl bg-[#153d30] p-3 text-white disabled:opacity-40">{busy?'Submitting…':'Submit for combined approval'}</button>{customerMode==='existing'&&!customers.length&&<p>No approved customers assigned to you yet. Choose a new customer if permitted.</p>}
 <LoanFinancialSummary preview loan={{...form,principal:Number(form.principal),balance:Number(form.principal),interest_rate:Number(form.interest_rate),status:'active'}}/></fieldset></form>}
 {message&&<p role="status" className="rounded bg-green-50 p-3 text-sm">{message}</p>}{error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm">{error}</p>}
 {(!agent||canSubmit)&&<><div className="flex gap-3 text-sm"><button disabled={busy} onClick={()=>void load()} className="underline">Refresh requests</button><button disabled={busy||page===0} onClick={()=>setPage(page-1)} className="disabled:opacity-40">Previous</button><span>Page {page+1}</span><button disabled={busy||!more} onClick={()=>setPage(page+1)} className="disabled:opacity-40">Next</button></div>
 {!rows.length&&!error&&<p className="text-sm">No loan submissions.</p>}{rows.map(r=><article key={r.id} className="space-y-2 rounded-xl border p-3 text-sm"><p className="break-all"><b>{r.status?.toUpperCase()}</b>{!agent&&<> · Reference {r.id}</>}</p><p>{new Date(Number(r.created_at)*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>{!agent&&<><p><b>{r.customer_name}</b> · Submitted by {r.agent_name}</p><p>Loan number: <b>{r.loan_number||r.loan_id||"Legacy request"}</b></p>{r.new_customer&&<p>New customer · {r.new_customer.phone} · {r.new_customer.occupation} · {r.new_customer.email||"No email"}<br/>Approval creates this customer and loan together, assigned to {r.agent_name}.</p>}<p>Principal: {money(Number(r.principal))} · Interest: {r.interest_rate}% ({r.interest_type}) · Return basis: {r.repayment_frequency}</p><p>Start: {r.given_date} · Next due: {r.next_due_date} · End: {r.end_date}</p><p>Security: {r.security_type} · Remarks: {r.remarks||'None'}</p>{r.review_reason&&<p>Decision reason: {r.review_reason}</p>}{r.status==='pending'&&<div className="flex flex-wrap gap-2"><input aria-label={'Review reason for '+r.id} placeholder="Review reason (optional, up to 1,000 characters)" maxLength={1000} disabled={busy} value={reasons[r.id!]||''} onChange={e=>setReasons({...reasons,[r.id!]:e.target.value})} className="min-w-0 flex-1 rounded border p-2"/>{['approve','reject'].map(action=><button key={action} disabled={busy} onClick={()=>void send({action,id:r.id,reason:reasons[r.id!]})} className="rounded border px-3 py-2 capitalize disabled:opacity-40">{action}</button>)}</div>}</>}</article>)}</>}
 </section>{agent&&<section className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-bold">Approved / existing assigned loans</h2><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr>{['Customer / loan','Principal','Balance','Interest','Return basis','Start / end','Next due','Status'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{loans.map(l=><tr key={l.id} className="border-t"><td className="p-2"><b>{l.customer_name}</b><p className="text-xs">Loan number: {l.loan_number||l.id}</p></td><td className="p-2">{money(l.principal)}{l.total_repayable!==undefined&&<p className="text-xs">Total: {money(l.total_repayable)}</p>}</td><td className="p-2">{money(l.balance)}</td><td className="p-2">{l.interest_rate}% {l.interest_model==='upfront_net_v1'?'deducted upfront':l.interest_model==='flat_term_v1'?'historical flat':l.interest_type}{l.interest_amount!=null&&<p className="text-xs">{money(l.interest_amount)}</p>}</td><td className="p-2">{l.repayment_frequency}</td><td className="p-2">{l.given_date}<br/>{l.end_date||'Not recorded'}</td><td className="p-2">{['flat_term_v1','upfront_net_v1'].includes(l.interest_model||'')?(l.next_payment_date||'Cleared'):l.next_due_date}{l.next_installment_due!==undefined&&<p className="text-xs">Due: {money(l.next_installment_due)}</p>}</td><td className="p-2">{l.status}</td></tr>)}</tbody></table></div>{!loans.length&&<p className="text-sm">No approved loans assigned to you.</p>}</section>}</div>;
}
