'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {LoanFinancialSummary} from './loan-financial-summary';
import type {LoanRequest} from '@/lib/loan-requests';
type Customer={id:string;name:string};
type ActiveLoan={interest_model?:string;interest_amount?:number;first_due_date?:string;total_repayable?:number;next_payment_date?:string|null;next_installment_due?:number;id:string;customer_name:string;principal:number;balance:number;interest_type:string;interest_rate:number;repayment_frequency:string;given_date:string;next_due_date:string;end_date:string;status:string;security_type:string;remarks:string|null};
const empty={customer_id:'',principal:'',interest_rate:'',interest_type:'fixed',repayment_frequency:'daily',given_date:'',next_due_date:'',end_date:'',security_type:'asset',remarks:''};
const money=(n:number)=>'₹'+Number(n).toLocaleString('en-IN');
export function LoanApprovals({agent,canSubmit=true}:{agent:boolean;canSubmit?:boolean}){
 const [rows,setRows]=useState<Partial<LoanRequest>[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[loans,setLoans]=useState<ActiveLoan[]>([]),[page,setPage]=useState(0),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState(empty),[reasons,setReasons]=useState<Record<string,string>>({});
 const requestId=useRef('');
 const load=useCallback(async()=>{try{
   if(!agent||canSubmit){const r=await fetch('/api/loan-requests?page='+page,{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.requests);setMore(d.hasMore);}
   if(agent){const r=await fetch('/api/data',{cache:'no-store'}),d=await r.json();if(!r.ok)throw new Error(d.error);setCustomers(d.customers);setLoans(d.loans);}
   setError('');
 }catch(e){setRows([]);setCustomers([]);setLoans([]);setError(e instanceof Error?e.message:'Could not load loan requests')}},[page,agent,canSubmit]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);const refresh=()=>void load();window.addEventListener('focus',refresh);window.addEventListener('fundflow-data',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('fundflow-data',refresh)}},[load]);
 async function send(body:Record<string,unknown>){if(busy)return;setBusy(true);setMessage('');setError('');try{
   const r=await fetch('/api/loan-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);
   setMessage(body.action==='submit'?'Submitted for Admin Manager approval. Reference: '+d.request.id:body.action==='approve'?'Loan approved for the submitting agent.':'Loan rejected. No active loan or balance was created.');
   if(body.action==='submit'){requestId.current='';setForm(empty);setOpen(false)}await load();window.dispatchEvent(new Event('fundflow-data'));
 }catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 const change=(key:keyof typeof empty,value:string)=>{requestId.current='';setForm({...form,[key]:value})};
 return <div className="space-y-6"><section className="mb-6 space-y-4 rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{agent?'My loans':'Agent loan approvals'}</h2>{agent&&canSubmit&&<button disabled={busy} onClick={()=>setOpen(!open)} className="rounded-xl bg-[#153d30] px-4 py-2 text-white">{open?'Close form':'Create loan'}</button>}</div><p className="text-sm text-[#61786c]">{agent?'Submit loans only for approved customers currently assigned to you. Pending loans show only their reference and status; details and collections unlock after approval.':'Review loan terms and approve or reject. Customer assignment and agent status are checked again at approval.'}</p>
 {agent&&canSubmit&&open&&<form onSubmit={e=>{e.preventDefault();requestId.current ||= crypto.randomUUID();void send({action:'submit',id:requestId.current,...form,principal:Number(form.principal),interest_rate:Number(form.interest_rate)})}}><fieldset disabled={busy} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
 <label className="text-sm">Assigned customer<select required value={form.customer_id} onChange={e=>change('customer_id',e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Choose approved customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · {c.id}</option>)}</select></label>
 <label className="text-sm">Loan amount (₹)<input required type="number" min="1" max="9007199254740991" step="1" value={form.principal} onChange={e=>change('principal',e.target.value)} className="mt-1 w-full rounded border p-2"/></label>
 <label className="text-sm">Flat interest for full term (%)<input required type="number" min="0" step="any" value={form.interest_rate} onChange={e=>change('interest_rate',e.target.value)} className="mt-1 w-full rounded border p-2"/></label>
 {([{key:'interest_type',label:'Interest type',options:['fixed']},{key:'repayment_frequency',label:'Return basis',options:['daily','weekly','monthly']},{key:'security_type',label:'Security type',options:['asset','surety']}] as const).map(f=><label key={f.key} className="text-sm">{f.label}<select value={form[f.key]} onChange={e=>change(f.key,e.target.value)} className="mt-1 w-full rounded border p-2">{f.options.map(o=><option key={o}>{o}</option>)}</select></label>)}
 {([{key:'given_date',label:'Start date'},{key:'next_due_date',label:'First due date'},{key:'end_date',label:'End date'}] as const).map(f=><label key={f.key} className="text-sm">{f.label}<input required type="date" min={f.key==='given_date'?'1900-01-01':form.given_date||'1900-01-01'} max={f.key==='next_due_date'?form.end_date||undefined:undefined} value={form[f.key]} onChange={e=>change(f.key,e.target.value)} className="mt-1 w-full rounded border p-2"/></label>)}
 <label className="text-sm sm:col-span-2">Remarks (optional)<textarea maxLength={2000} value={form.remarks} onChange={e=>change('remarks',e.target.value)} className="mt-1 w-full rounded border p-2"/></label><button disabled={!customers.length} className="self-end rounded-xl bg-[#153d30] p-3 text-white disabled:opacity-40">{busy?'Submitting…':'Submit for approval'}</button>{!customers.length&&<p>No approved customers assigned to you yet.</p>}
 <LoanFinancialSummary preview loan={{...form,principal:Number(form.principal),balance:Number(form.principal),interest_rate:Number(form.interest_rate),status:'active'}}/></fieldset></form>}
 {message&&<p role="status" className="rounded bg-green-50 p-3 text-sm">{message}</p>}{error&&<p role="alert" className="rounded bg-red-50 p-3 text-sm">{error}</p>}
 {(!agent||canSubmit)&&<><div className="flex gap-3 text-sm"><button disabled={busy} onClick={()=>void load()} className="underline">Refresh requests</button><button disabled={busy||page===0} onClick={()=>setPage(page-1)} className="disabled:opacity-40">Previous</button><span>Page {page+1}</span><button disabled={busy||!more} onClick={()=>setPage(page+1)} className="disabled:opacity-40">Next</button></div>
 {!rows.length&&!error&&<p className="text-sm">No loan submissions.</p>}{rows.map(r=><article key={r.id} className="space-y-2 rounded-xl border p-3 text-sm"><p className="break-all"><b>{r.status?.toUpperCase()}</b> · Reference {r.id}</p><p>{new Date(Number(r.created_at)*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST</p>{!agent&&<><p><b>{r.customer_name}</b> · Submitted by {r.agent_name}</p><p>Principal: {money(Number(r.principal))} · Interest: {r.interest_rate}% ({r.interest_type}) · Return basis: {r.repayment_frequency}</p><p>Start: {r.given_date} · Next due: {r.next_due_date} · End: {r.end_date}</p><p>Security: {r.security_type} · Remarks: {r.remarks||'None'}</p>{r.review_reason&&<p>Decision reason: {r.review_reason}</p>}{r.status==='pending'&&<div className="flex flex-wrap gap-2"><input aria-label={'Review reason for '+r.id} placeholder="Review reason (optional, up to 1,000 characters)" maxLength={1000} disabled={busy} value={reasons[r.id!]||''} onChange={e=>setReasons({...reasons,[r.id!]:e.target.value})} className="min-w-0 flex-1 rounded border p-2"/>{['approve','reject'].map(action=><button key={action} disabled={busy} onClick={()=>void send({action,id:r.id,reason:reasons[r.id!]})} className="rounded border px-3 py-2 capitalize disabled:opacity-40">{action}</button>)}</div>}</>}</article>)}</>}
 </section>{agent&&<section className="rounded-2xl border bg-white p-5"><h2 className="mb-4 font-bold">Approved / existing assigned loans</h2><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-sm"><thead><tr>{['Customer / loan','Principal','Balance','Interest','Return basis','Start / end','Next due','Status'].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{loans.map(l=><tr key={l.id} className="border-t"><td className="p-2"><b>{l.customer_name}</b><p className="max-w-60 break-all text-xs">{l.id}</p><p className="text-xs">{l.security_type} · {l.remarks||'No remarks'}</p></td><td className="p-2">{money(l.principal)}{l.total_repayable!==undefined&&<p className="text-xs">Total: {money(l.total_repayable)}</p>}</td><td className="p-2">{money(l.balance)}</td><td className="p-2">{l.interest_rate}% {l.interest_model==='flat_term_v1'?'flat / full term':l.interest_type}{l.interest_amount!=null&&<p className="text-xs">{money(l.interest_amount)}</p>}</td><td className="p-2">{l.repayment_frequency}</td><td className="p-2">{l.given_date}<br/>{l.end_date||'Not recorded'}</td><td className="p-2">{l.interest_model==='flat_term_v1'?(l.next_payment_date||'Cleared'):l.next_due_date}{l.next_installment_due!==undefined&&<p className="text-xs">Due: {money(l.next_installment_due)}</p>}</td><td className="p-2">{l.status}</td></tr>)}</tbody></table></div>{!loans.length&&<p className="text-sm">No approved loans assigned to you.</p>}</section>}</div>;
}
