'use client';
import {useEffect,useState} from 'react';
import {type Permission} from '@/lib/permissions';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {ReceiptCorrections} from './receipt-corrections';
import {CollectionLedger} from './collection-ledger';
import {categorizeCollections} from '@/lib/collection-frequency';
export function ManagerPortal({active,permissions,open}:{active:string;permissions:Permission[];open:(modal:'customer'|'loan'|'payment')=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[form,setForm]=useState<any>(null),[busy,setBusy]=useState(false);
 const load=async()=>{try{const r=await fetch('/api/data',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('')}catch(e){setData(null);setError(e instanceof Error?e.message:'Loading failed')}};
 useEffect(()=>{void load();window.addEventListener('fundflow-data',load);window.addEventListener('focus',load);return()=>{window.removeEventListener('fundflow-data',load);window.removeEventListener('focus',load)}},[]);
 const can=(p:Permission)=>permissions.includes(p),money=(v:any)=>'₹'+Number(v||0).toLocaleString('en-IN');
 const submit=async()=>{if(busy)return;setBusy(true);try{const r=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);setForm(null);await load();window.dispatchEvent(new Event('fundflow-data'));if(d.blocked_ids?.length)setError('Some customers were retained because loans are open or unpaid.')}catch(e){setError(e instanceof Error?e.message:'Save failed')}finally{setBusy(false)}};
 const exportReport=()=>{const records=[['Type','ID','Name','Amount / balance'],...data.customers.map((r:any)=>['Customer',r.id,r.name,r.outstanding]),...data.loans.map((r:any)=>['Loan',r.id,r.customer_name,r.balance]),...data.collections.map((r:any)=>['Collection',r.id,r.customer_name,r.amount])];const csv=records.map((r:any[])=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='RMV-Finance-Manager-Report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 const customers=active==='Customers',loans=active==='Loans',agents=active==='Agents',reports=active==='Reports';
 const rows=data?(customers?data.customers:loans?data.loans:agents?data.agents:data.collections):[];
 const action=(label:string,fn:()=>void)=><button onClick={fn} className="rounded border px-3 py-1 text-sm">{label}</button>;
 return <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold">{active}</h1><p className="mt-2 text-sm text-[#6c8078]">Admin Manager · all collection agents and permitted records</p></div><div className="flex flex-wrap gap-2">{customers&&can('create_customer')&&action('Create customer',()=>open('customer'))}{loans&&can('create_loan')&&action('Create loan',()=>open('loan'))}{agents&&can('create_agent')&&action('Create collection agent',()=>setForm({action:'create_agent',name:'',phone:'',username:'',password:''}))}{active==='Collections'&&can('create_collection')&&action('Record collection',()=>open('payment'))}{reports&&data&&action('Download report',exportReport)}</div></div>{error&&<p role="alert" className="rounded border border-red-200 bg-red-50 p-3">{error}</p>}{!data?<button onClick={load}>Load records</button>:<>
 {reports&&<div className="grid gap-3 sm:grid-cols-3">{[['Customers',data.customers.length],['Loans',data.loans.length],['Recorded collections',money(data.collections.reduce((s:number,r:any)=>s+Number(r.amount),0))]].map(([label,value])=><div key={label} className="rounded-xl border bg-white p-5"><p>{label}</p><b>{value}</b></div>)}</div>}
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-sm"><thead><tr>{['Record','Details','Amount / assignment','Actions'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map((r:any)=><tr key={r.id} className="border-t"><td className="p-3"><b>{r.name||r.customer_name}</b><p className="text-xs">{r.id}</p></td><td className="p-3">{customers?`${r.phone} · ${r.occupation||'Occupation not recorded'}`:loans?`${r.given_date} → ${r.end_date||'End date not recorded'}`:agents?`${r.phone} · ${r.assigned} assigned customers`:new Date(r.collected_at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td className="p-3">{agents?money(r.collected):money(customers?r.outstanding:loans?r.balance:r.amount)}</td><td className="flex flex-wrap gap-2 p-3">
 {customers&&can('update_customer')&&action('Edit',()=>setForm({action:'update_customer',id:r.id,name:r.name,phone:r.phone,email:r.email||'',occupation:r.occupation||''}))}
 {customers&&can('assign_customer')&&action('Assign agent',()=>setForm({action:'assign_customer',customer_id:r.id,agent_id:r.assigned_agent_id||''}))}
 {customers&&can('delete_customers')&&action('Delete',()=>setForm({action:'delete_customers',ids:[r.id]}))}
 {loans&&can('update_loan')&&action('Edit',()=>setForm({action:'update_loan',id:r.id,interest_rate:r.interest_rate,next_due_date:r.next_due_date,end_date:r.end_date||'',repayment_frequency:r.repayment_frequency,remarks:r.remarks||''}))}
 {agents&&can('update_agent')&&action('Edit',()=>setForm({action:'update_agent',id:r.id,name:r.name,phone:r.phone,username:r.username||'',password:''}))}
 {agents&&can('delete_agent')&&action('Archive',()=>setForm({action:'delete_agent',id:r.id}))}
 </td></tr>)}{!rows.length&&<tr><td colSpan={4} className="p-5">No records.</td></tr>}</tbody></table></div>
 {active==='Collections'&&can('request_correction')&&<ReceiptCorrections receipts={data.collections} role="manager"/>}
 {active==='Collections'&&['daily','weekly','monthly'].map(f=><CollectionLedger key={f} frequency={f} receipts={categorizeCollections(data.loans,data.collections as {loan_id:string;amount:number;collected_at:number}[],f).collections}/>)}</>}
 <Dialog open={Boolean(form)} onOpenChange={v=>!v&&!busy&&setForm(null)}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{form?.action?.replaceAll('_',' ')}</DialogTitle><DialogDescription>Only granted actions are available. Changes are recorded in the audit log.</DialogDescription></DialogHeader>{form&&<form onSubmit={e=>{e.preventDefault();void submit()}} className="grid gap-3 sm:grid-cols-2">{Object.keys(form).filter(k=>!['action','id','ids','customer_id'].includes(k)).map(k=><label key={k} className="text-sm capitalize">{k.replaceAll('_',' ')}{k==='agent_id'?<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded border p-2"><option value="">Unassigned</option>{data?.agents.map((a:any)=><option key={a.id} value={a.id}>{a.name}</option>)}</select>:k==='repayment_frequency'?<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded border p-2">{['daily','weekly','monthly','yearly'].map(f=><option key={f}>{f}</option>)}</select>:<input required={!['email','remarks','password'].includes(k)||(k==='password'&&form.action==='create_agent')} autoComplete={k==='password'?'new-password':'off'} type={k==='password'?'password':k.includes('date')?'date':k==='interest_rate'?'number':'text'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="mt-1 w-full rounded border p-2"/>}</label>)}{form.action.startsWith('delete')&&<p>Confirm removal? Customers with open or unpaid loans cannot be deleted.</p>}{error&&<p role="alert">{error}</p>}<button disabled={busy} className="rounded-xl bg-[#153d30] p-3 text-white sm:col-span-2">{busy?'Saving…':'Confirm'}</button></form>}</DialogContent></Dialog>
 </div>;
}
