'use client';
import {useEffect,useRef,useState} from 'react';
import type {ReceiptCorrection} from '@/lib/receipt-corrections';
type Receipt={id:string;amount:number;loan_id:string;customer_name?:string;correction_id?:string|null};
export function ReceiptCorrections({receipts,role}:{receipts:Receipt[];role:'admin'|'manager'}){
 const [requests,setRequests]=useState<ReceiptCorrection[]>([]),[id,setId]=useState(''),[amount,setAmount]=useState(''),[reason,setReason]=useState(''),[review,setReview]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const key=useRef('');const selected=receipts.find(r=>r.id===id);
 const load=async()=>{const r=await fetch('/api/receipt-corrections',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setRequests(d.requests)};
 useEffect(()=>{void load().catch(e=>setMessage(e.message))},[]);
 const send=async(body:Record<string,unknown>)=>{if(busy)return;setBusy(true);setMessage('');try{const r=await fetch('/api/receipt-corrections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.request.status==='pending'?'Submitted. Ledger unchanged until Super Admin approval.':d.request.status==='approved'?'Correction applied. Loan balance and ledger totals updated.':'Request rejected. Financial values unchanged.');key.current='';setReason('');setAmount('');await load();window.dispatchEvent(new Event('fundflow-data'))}catch(e){setMessage(e instanceof Error?e.message:'Correction failed')}finally{setBusy(false)}};
 return <section className="mt-6 space-y-4 rounded-2xl border bg-white p-5"><h2 className="font-bold">Receipt corrections & approvals</h2><p className="text-sm">Correct an individual receipt amount, not an aggregate total. Original receipts and signatures are preserved. Zero reverses the payment. {role==='manager'?'Super Admin approval is required.':'Approved changes recalculate the loan balance and all ledger totals.'}</p>
 <form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();if(!selected)return;key.current ||= crypto.randomUUID();void send({action:'request',id:key.current,receipt_id:id,amount:Number(amount),before_amount:selected.amount,base_revision:selected.correction_id||null,reason})}}>
 <label>Receipt<select required disabled={busy} className="mt-1 w-full rounded border p-2" value={id} onChange={e=>{setId(e.target.value);setAmount('');key.current=''}}><option value="">Choose receipt</option>{receipts.map(r=><option key={r.id} value={r.id}>{r.id} · {r.customer_name||r.loan_id} · ₹{r.amount.toLocaleString('en-IN')}</option>)}</select></label>
 <label>Corrected amount (₹)<input required disabled={busy} type="number" min="0" step="1" value={amount} className="mt-1 w-full rounded border p-2" onChange={e=>{setAmount(e.target.value);key.current=''}}/></label>
 <label className="sm:col-span-2">Reason (required)<textarea required disabled={busy} minLength={10} maxLength={1000} value={reason} className="mt-1 w-full rounded border p-2" onChange={e=>{setReason(e.target.value);key.current=''}}/></label><button disabled={busy||!selected} className="rounded bg-[#153d30] p-3 text-white disabled:opacity-50">{busy?'Processing…':role==='admin'?'Apply correction':'Submit for approval'}</button></form>
 {message&&<p role="status" className="rounded border p-3">{message}</p>}<button disabled={busy} onClick={()=>void load().catch(e=>setMessage(e.message))} className="text-sm underline">Refresh requests</button>
 <h3 className="font-bold">{role==='admin'?'Recent requests (all collection categories)':'Your recent requests'}</h3>{!requests.length&&<p className="text-sm">No correction requests.</p>}{requests.map(r=><article key={r.id} className="space-y-2 rounded border p-3 text-sm"><p><b>{r.receipt_id}</b> · ₹{r.before_amount.toLocaleString('en-IN')} → ₹{r.after_amount.toLocaleString('en-IN')} · <b>{r.status}</b></p><p>{r.requested_name}: {r.reason}</p>{r.reviewed_name&&<p>{r.reviewed_name}: {r.review_reason}</p>}{role==='admin'&&r.status==='pending'&&<div className="flex flex-wrap gap-2"><input aria-label={'Review reason for '+r.receipt_id} placeholder="Approval / rejection reason (10+ characters)" value={review[r.id]||''} maxLength={1000} disabled={busy} onChange={e=>setReview({...review,[r.id]:e.target.value})} className="min-w-0 flex-1 rounded border p-2"/>{(['approve','reject'] as const).map(action=><button key={action} disabled={busy||(review[r.id]||'').trim().length<10} onClick={()=>void send({action,id:r.id,reason:review[r.id]})} className="rounded border p-2 capitalize disabled:opacity-50">{action}</button>)}</div>}</article>)}</section>;
}
